force-app/main/default/objects/Default_vendor_contact__c/Default_vendor_contact__c.object-meta.xml
<CustomObject>
    <description>Connector between a Vendor and corresponding unique contact that&apos;s the &quot;default&quot; contact</description>
    <label>Default vendor contact</label>
    <nameField>
        <label>Default contact for vendor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Default vendor contact</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Default_vendor_contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Default vendor contact</relationshipLabel>
    <relationshipName>Default_vendor_contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Default_vendor_contact__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Default vendor contact</relationshipLabel>
    <relationshipName>Default_vendor_contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Function title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Positions (Position)</relationshipLabel>
    <relationshipName>Positions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_position_application__c/Vendor_position_application__c.object-meta.xml
<CustomObject>
    <description>Object used to store information about applications on a position per vendor, such as number of applications a vendor has made on a position.</description>
    <label>Vendor position application</label>
    <nameField>
        <label>Vendor position application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor position applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_position_application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Vendor position applications</relationshipLabel>
    <relationshipName>Vendor_position_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_position_application__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendor position applications</relationshipLabel>
    <relationshipName>Vendor_position_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VendorPositionApplicationHandlerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class VendorPositionApplicationHandlerTest {

    @isTest
    static void testShareWithVendor() {
        Account v = TestDataFactory.getVendor();
        insert v;

        Contact c = [SELECT Id FROM Contact WHERE Id IN (SELECT Contact__c FROM Default_vendor_contact__c WHERE Vendor__c = :v.Id) LIMIT 1];

        User u = TestDataFactory.getPortalUser(v, c);
        insert u;

        Position__c p = TestDataFactory.getPosition(false);
        insert p;

        Vendor_position_application__c vpa = new Vendor_position_application__c();
        vpa.Vendor__c = v.Id;
        vpa.Position__c = p.Id;
        insert vpa;

        List<Position__Share> shares = [SELECT Id, UserOrGroupId, AccessLevel, 
        RowCause FROM Position__Share WHERE ParentId = :p.Id AND UserOrGroupId= :u.Id];

        System.assertEquals(1, shares.size());

        System.assertEquals(shares[0].AccessLevel, 'Read');
        System.assertEquals(shares[0].RowCause, Schema.Position__Share.RowCause.Hiring_desk_to_vendor__c);
    }
}