force-app/main/default/objects/Default_vendor_contact__c/Default_vendor_contact__c.object-meta.xml
<CustomObject>
    <description>Connector between a Vendor and corresponding unique contact that&apos;s the &quot;default&quot; contact</description>
    <label>Default vendor contact</label>
    <nameField>
        <label>Default contact for vendor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Default vendor contact</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Default_vendor_contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Default vendor contact</relationshipLabel>
    <relationshipName>Default_vendor_contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Default_vendor_contact__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Default vendor contact</relationshipLabel>
    <relationshipName>Default_vendor_contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mailtemplate__c/Mailtemplate__c.object-meta.xml
<CustomObject>
    <label>Mailtemplate</label>
    <nameField>
        <label>Mailtemplate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mailtemplates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Mailtemplate_account__c/Mailtemplate_account__c.object-meta.xml
<CustomObject>
    <label>Mailtemplate account</label>
    <nameField>
        <label>Mailtemplate account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mailtemplates accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Mailtemplate_account__c/fields/Mailtemplate__c.field-meta.xml
<CustomField>
    <fullName>Mailtemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mailtemplate</label>
    <referenceTo>Mailtemplate__c</referenceTo>
    <relationshipLabel>Mailtemplates accounts</relationshipLabel>
    <relationshipName>Mailtemplates_accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Function title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Hourly_rate__c.field-meta.xml
<CustomField>
    <fullName>Hourly_rate__c</fullName>
    <description>Expected hourly rate</description>
    <label>Hourly rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Positions (Position)</relationshipLabel>
    <relationshipName>Positions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MailWrapperTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class MailWrapperTest {

    @isTest
    static void testCreateWrapperFindTemplate() {
        User u = TestDataFactory.getUser();

        insert u;

        Position__c pos = TestDataFactory.getPosition(false);
        pos.Hourly_rate__c = 60;
        Account v = TestDataFactory.getVendor();

        insert v;
        Default_vendor_contact__c cont = [SELECT Contact__c FROM Default_vendor_contact__c WHERE Vendor__c = :v.Id];
        Mailtemplate__c mt = TestDataFactory.getMailTemplate('New position: {{Name}}', 'Please find us some peeps for {{Hourly_rate__c}}.');
        
        System.runAs(u) {
            insert pos;
            insert mt;

            Mailtemplate_account__c connector = TestDataFactory.connectMailTemplateAccount(u.AccountId__c, mt.Id, 'Distribution_email');

            insert connector;

            MailWrapper mw = new MailWrapper(pos.Id, cont.Contact__c, 'Distribution_email', false);
        }
    }

    @isTest
    static void testCreateDontFindTemplate() {
        User u = TestDataFactory.getUser();

        insert u;

        Position__c pos = TestDataFactory.getPosition(false);
        pos.Hourly_rate__c = 60;

        Account v = TestDataFactory.getVendor();

        insert v;
        Default_vendor_contact__c cont = [SELECT Contact__c FROM Default_vendor_contact__c WHERE Vendor__c = :v.Id];

        Mailtemplate__c mt = TestDataFactory.getMailTemplate('New position: {{Name}}', 'Please find us some peeps for {{Hourly_rate__c}}.');
        
        System.runAs(u) {
            try {
                insert pos;
                insert mt;

                Test.startTest();
                MailWrapper mw = new MailWrapper(pos.Id, cont.Contact__c, 'Distribution_email', false);
                Test.stopTest();

                System.Assert.fail();
            }
            catch (Exception e) {
                System.assertEquals('MailWrapper.MailWrapperException', e.getTypeName());
            }
        }
    }
}