force-app/main/default/objects/Default_vendor_contact__c/Default_vendor_contact__c.object-meta.xml
<CustomObject>
    <description>Connector between a Vendor and corresponding unique contact that&apos;s the &quot;default&quot; contact</description>
    <label>Default vendor contact</label>
    <nameField>
        <label>Default contact for vendor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Default vendor contact</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Default_vendor_contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Default vendor contact</relationshipLabel>
    <relationshipName>Default_vendor_contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Default_vendor_contact__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Default vendor contact</relationshipLabel>
    <relationshipName>Default_vendor_contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Function title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Positions (Position)</relationshipLabel>
    <relationshipName>Positions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_position_application__c/Vendor_position_application__c.object-meta.xml
<CustomObject>
    <description>Object used to store information about applications on a position per vendor, such as number of applications a vendor has made on a position.</description>
    <label>Vendor position application</label>
    <nameField>
        <label>Vendor position application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor position applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_position_application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Vendor position applications</relationshipLabel>
    <relationshipName>Vendor_position_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_position_application__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendor position applications</relationshipLabel>
    <relationshipName>Vendor_position_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VendorPositionApplicationTriggerHandler.cls
public without sharing class VendorPositionApplicationTriggerHandler {
    private System.TriggerOperation triggerOperation;
	private List<Vendor_position_application__c> newList;
	private List<Vendor_position_application__c> oldList;
	private Map<Id, Vendor_position_application__c> newMap;
	private Map<Id, Vendor_position_application__c> oldMap;
    
    public VendorPositionApplicationTriggerHandler(System.TriggerOperation triggerOperation, List<Vendor_position_application__c> newList, List<Vendor_position_application__c> oldList, Map<Id, Vendor_position_application__c> newMap, Map<Id, Vendor_position_application__c> oldMap) {
        this.triggerOperation = triggerOperation;
		this.newList = newList;
		this.newMap = newMap;
		this.oldMap = oldMap;
		this.oldList = oldList;
    }

    public void execute() {
		switch on this.triggerOperation {
			when BEFORE_INSERT {
			}
			when AFTER_INSERT {
                sharePositionWithVendors(this.newList);
			}
			when BEFORE_UPDATE{
			}
			when AFTER_UPDATE {
			}
			when AFTER_DELETE {
			}
		}
    }

    public static void sharePositionWithVendors(List<Vendor_position_application__c> newList) {
        if (newList.size() > 0) {
            Id positionId = newList[0].Position__c;
            List<Id> vendorIds = new List<Id>();

			// Get ids of vendors
            for (Vendor_position_application__c vpa: newList) {
				if (!String.isBlank(vpa.Vendor__c)) {
					vendorIds.add(vpa.Vendor__c);
				}
            }

			// Get ids of users associated with default vendor contacts
			List<User> vendorUsers = [SELECT Id FROM User WHERE ContactId IN (
				SELECT Contact__c FROM Default_vendor_contact__c WHERE Vendor__c IN :vendorIds)];

			List<Id> userIds = new List<Id>(DeveloperUtils.getIdFieldSet(vendorUsers, 'Id'));

            PositionSharingHandler.shareRecordWithVendors(positionId, userIds);
        }
    }
}