force-app/main/default/objects/Default_vendor_contact__c/Default_vendor_contact__c.object-meta.xml
<CustomObject>
    <description>Connector between a Vendor and corresponding unique contact that&apos;s the &quot;default&quot; contact</description>
    <label>Default vendor contact</label>
    <nameField>
        <label>Default contact for vendor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Default vendor contact</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Default_vendor_contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Default vendor contact</relationshipLabel>
    <relationshipName>Default_vendor_contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Default_vendor_contact__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Default vendor contact</relationshipLabel>
    <relationshipName>Default_vendor_contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement__c/Placement__c.object-meta.xml
<CustomObject>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Placement__c/fields/Professional__c.field-meta.xml
<CustomField>
    <fullName>Professional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Professional</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Placements</relationshipLabel>
    <relationshipName>Placements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Placements (Vendor)</relationshipLabel>
    <relationshipName>Placements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PlacementSharingHandler.cls
public without sharing class PlacementSharingHandler {
    public class PlacementSharingException extends Exception {}

    public static void sharePlacementWithVendor(Id placementId) {
        Id vendorId = [
            SELECT Vendor__c
            FROM Placement__c
            WHERE Id = :placementId
            LIMIT 1
        ].Vendor__c;

        List<User> vendorUser = [
            SELECT Id
            FROM User
            WHERE ContactId IN (
                SELECT Contact__c
                FROM Default_vendor_contact__c
                WHERE Vendor__c = :vendorId
            )
        ];

        if (vendorUser == null || vendorUser.size() == 0) {
            throw new PlacementSharingException('Could not find vendor contact for placement with Id ' + placementId);
        }

        SharingHandler.shareRecord(placementId, vendorUser[0].Id, SharingHandler.AccessLevel.READ, Schema.Placement__Share.RowCause.Vendor__c, 'Placement__Share');
    }

    public static void sharePlacementWithProfessional(Id placementId) {
        List<User> professional = [
            SELECT Id 
            FROM User 
            WHERE ContactId IN (
                SELECT Professional__c FROM Placement__c WHERE Id = :placementId
            )
        ];

        if (professional == null || professional.size() == 0) {
            throw new PlacementSharingException('Could not professional associated with placement with Id ' + placementId);
        }
        SharingHandler.shareRecord(placementId, professional[0].Id, SharingHandler.AccessLevel.READ, Schema.Placement__Share.RowCause.Professional__c, 'Placement__Share');
    }
}