force-app/main/default/objects/Placement__c/Placement__c.object-meta.xml
<CustomObject>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Placement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Placements</relationshipLabel>
    <relationshipName>Account_for_placements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Contracts_Id__c.field-meta.xml
<CustomField>
    <fullName>Contracts_Id__c</fullName>
    <description>This is the ID that is returned when the placement gets posted from VMS -&gt; Hero Salesforce</description>
    <externalId>true</externalId>
    <label>Contracts Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Placements</relationshipLabel>
    <relationshipName>Position_for_placements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Processing_status__c.field-meta.xml
<CustomField>
    <fullName>Processing_status__c</fullName>
    <label>Processing status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In review by hiring desk</fullName>
            </value>
            <value>
                <fullName>Sent for contracting</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Purchase_contract_status__c.field-meta.xml
<CustomField>
    <fullName>Purchase_contract_status__c</fullName>
    <label>Purchase contract status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contract_status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Sales_contract_status__c.field-meta.xml
<CustomField>
    <fullName>Sales_contract_status__c</fullName>
    <label>Sales contract status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contract_status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Placement_rate_percentage__c/Placement_rate_percentage__c.object-meta.xml
<CustomObject>
    <label>Placement rate percentage</label>
    <nameField>
        <label>Placement rate percentage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement rate percentages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Placement_rate_percentage__c/fields/Placement__c.field-meta.xml
<CustomField>
    <fullName>Placement__c</fullName>
    <label>Placement</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Placement rate percentages</relationshipLabel>
    <relationshipName>Placement_rate_percentages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Function title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Account_for_positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Number_of_hires__c.field-meta.xml
<CustomField>
    <fullName>Number_of_hires__c</fullName>
    <label>Number of hires</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Positions (Position)</relationshipLabel>
    <relationshipName>Positions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Processing_status__c.field-meta.xml
<CustomField>
    <fullName>Processing_status__c</fullName>
    <label>Processing status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Distributed</fullName>
            </value>
            <value>
                <fullName>Candidates offered and in review of manager</fullName>
            </value>
            <value>
                <fullName>Interviews planned</fullName>
            </value>
            <value>
                <fullName>Placement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Afgewezen</label>
            </value>
            <value>
                <fullName>Concept</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Applications with hiring manager</fullName>
                <isActive>false</isActive>
                <label>Applications with hiring manager</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Sent to hiring manager</fullName>
                <isActive>false</isActive>
                <label>Sent to hiring manager</label>
            </value>
            <value>
                <fullName>Unapproved</fullName>
                <isActive>false</isActive>
                <label>Unapproved</label>
            </value>
            <value>
                <fullName>Up for correction</fullName>
                <isActive>false</isActive>
                <label>Up for correction</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PlacementTriggerHandlerTest.cls
@istest
public class PlacementTriggerHandlerTest {
	@istest
	static void postToHeroOrg() {
		Placement__c placement = new Placement__c();

		Test.startTest();
		insert placement;
		Test.stopTest();
	}

	@istest
	static void postToHeroOrgWithContractsPlacementId() {
		Placement__c randomPlacement = new Placement__c();
		insert randomPlacement;

		Placement__c placement = new Placement__c();
		insert placement;

		placement.Contracts_Id__c = randomPlacement.Id;
		
		Test.startTest();
		update placement;
		Test.stopTest();
	}

	@istest
	static void testStatusActive(){
		Placement__c pl = TestDataFactory.getPlacement();
		pl.Status__c = 'New';
		insert pl;

		Test.startTest();
		pl.Sales_contract_status__c = 'Signed';
		pl.Purchase_contract_status__c = 'Signed';
		update pl;
		Test.stopTest();

		Assert.areEqual('Active', [SELECT Id, Processing_Status__c FROM Placement__c WHERE Id = :pl.Id].Processing_Status__c);
	}

	@istest
	static void testRelateStandardRatePercentage(){
		Placement__c pl = TestDataFactory.getPlacementWithRatePercentage();

		Test.startTest();
		Placement__c newPlacement = new Placement__c();
		newPlacement.Account__c = pl.Account__c;
		insert newPlacement;
		Test.stopTest();

		Assert.areEqual(1, [SELECT Id FROM Placement_rate_percentage__c WHERE Placement__c = :newPlacement.Id].size());
	}

	@istest
	static void testCheckStatusOnPosition(){
		Account acc = TestDataFactory.getAccount();
		insert acc;

		Position__c pos = TestDataFactory.getPosition(false);
		pos.Number_of_hires__c = '1';
		insert pos;

		Test.startTest();
		Placement__c pl = TestDataFactory.getPlacement();
		pl.Position__c = pos.Id;
		pl.Status__c = 'New';
		insert pl;
		Test.stopTest();

		Assert.areEqual('Hired', [SELECT Id, Status__c FROM Position__c WHERE Id = :pos.Id].Status__c);
	}

	@istest
	static void testCheckStatusOnPositionNotHired(){
		Account acc = TestDataFactory.getAccount();
		insert acc;

		Position__c pos = TestDataFactory.getPosition(false);
		pos.Number_of_hires__c = '2';
		insert pos;

		Test.startTest();
		Placement__c pl = TestDataFactory.getPlacement();
		pl.Position__c = pos.Id;
		pl.Status__c = 'New';
		insert pl;
		Test.stopTest();

		Assert.areEqual('Open', [SELECT Id, Status__c FROM Position__c WHERE Id = :pos.Id].Status__c);
	}

	@istest
	static void testCheckStatusOnPositionHiredMultiple(){
		Account acc = TestDataFactory.getAccount();
		insert acc;

		Position__c pos = TestDataFactory.getPosition(false);
		pos.Number_of_hires__c = '2';
		insert pos;

		Placement__c pl = TestDataFactory.getPlacement();
		pl.Position__c = pos.Id;
		pl.Status__c = 'New';
		insert pl;

		Test.startTest();
		Placement__c pl1 = new Placement__c();
		pl1.Position__c = pos.Id;
		pl1.Status__c = 'New';
		insert pl1;
		Test.stopTest();

		Assert.areEqual('Hired', [SELECT Id, Status__c FROM Position__c WHERE Id = :pos.Id].Status__c);
	}
}