force-app/main/default/objects/Placement__c/Placement__c.object-meta.xml
<CustomObject>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Placement_rate_percentage__c/Placement_rate_percentage__c.object-meta.xml
<CustomObject>
    <label>Placement rate percentage</label>
    <nameField>
        <label>Placement rate percentage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement rate percentages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Placement_rate_percentage__c/fields/Placement__c.field-meta.xml
<CustomField>
    <fullName>Placement__c</fullName>
    <label>Placement</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Placement rate percentages</relationshipLabel>
    <relationshipName>Placement_rate_percentages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Placement_rate_percentage__c/fields/Rate_percentage__c.field-meta.xml
<CustomField>
    <fullName>Rate_percentage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate percentage</label>
    <referenceTo>Rate_percentage__c</referenceTo>
    <relationshipLabel>Placement rate percentages</relationshipLabel>
    <relationshipName>Placement_rate_percentages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rate_percentage__c/Rate_percentage__c.object-meta.xml
<CustomObject>
    <label>Rate percentage</label>
    <nameField>
        <label>Rate percentage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate percentages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RatePercentageSelectorControllerTest.cls
@istest
public class RatePercentageSelectorControllerTest {
   
    @istest
    public static void getRatePercentageTest(){
        Placement__c pl = TestDataFactory.getPlacementWithRatePercentage();

        Test.startTest();
        RatePercentageSelectorController.RatePercentageWrapper wrapper = RatePercentageSelectorController.getRatePercentages(pl.id);
        Test.stopTest();

        Assert.isNotNull(wrapper);
        Assert.areEqual(1, wrapper.selectedRatePercentageList.size());
        Assert.areEqual(1, wrapper.notSelectedRatePercentageList.size());

    }

    @istest
    public static void saveRatePercentageTest(){
        Placement__c pl = TestDataFactory.getPlacementWithRatePercentage();

        List<Rate_percentage__c> rps = [SELECT id FROM Rate_percentage__c];
        List<String> rpsIds = new List<String>();
        for(Rate_percentage__c rp : rps){
            rpsIds.add(rp.Id);
        }

        Test.startTest();
        String result = RatePercentageSelectorController.saveRatePercentages(rpsIds, pl.id);
        Test.stopTest();

        Assert.isNotNull(result);
        Assert.areEqual(1, [SELECT Id FROM Placement_rate_percentage__c].size());
    }

    @istest
    public static void saveRatePercentageDeleteTest(){
        Placement__c pl = TestDataFactory.getPlacementWithRatePercentage();

        List<Rate_percentage__c> rps = [SELECT id FROM Rate_percentage__c];
        List<String> rpsIds = new List<String>();

        Test.startTest();
        String result = RatePercentageSelectorController.saveRatePercentages(rpsIds, pl.id);
        Test.stopTest();

        Assert.isNotNull(result);
        Assert.areEqual(0, [SELECT Id FROM Placement_rate_percentage__c].size());
    }
}