force-app/main/default/objects/Placement__c/Placement__c.object-meta.xml
<CustomObject>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Placement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Placements</relationshipLabel>
    <relationshipName>Account_for_placements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Approver_timesheets__c.field-meta.xml
<CustomField>
    <fullName>Approver_timesheets__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver timesheets</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Placements (Approver timesheets)</relationshipLabel>
    <relationshipName>Timesheets_approver</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Create_timesheet__c.field-meta.xml
<CustomField>
    <fullName>Create_timesheet__c</fullName>
    <formula>AND(
  (IF(ISBLANK(Timesheets_created_till__c),true,
     IF(Timesheets_created_till__c &lt;&gt;  Expected_end_date__c, true, false))),
  (NOT(ISBLANK(Start_date__c))),
  (NOT(ISBLANK(Expected_end_date__c))),
  (NOT(ISBLANK(TEXT(Timesheet_date_notation__c)))),
  (NOT(ISBLANK(Timesheet_size__c))),
  (NOT(ISBLANK(Professional__c))),
  (NOT(ISBLANK(Approver_timesheets__c)))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Create timesheet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Expected_end_date__c.field-meta.xml
<CustomField>
    <fullName>Expected_end_date__c</fullName>
    <label>Expected end date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Professional__c.field-meta.xml
<CustomField>
    <fullName>Professional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Professional</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Placements</relationshipLabel>
    <relationshipName>Placements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Timesheet_date_notation__c.field-meta.xml
<CustomField>
    <fullName>Timesheet_date_notation__c</fullName>
    <label>Timesheet date notation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Timesheet_date_notation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Timesheet_size__c.field-meta.xml
<CustomField>
    <fullName>Timesheet_size__c</fullName>
    <label>Timesheet size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Timesheets_created_till__c.field-meta.xml
<CustomField>
    <fullName>Timesheets_created_till__c</fullName>
    <label>Timesheets created till</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TimesheetBatch.cls
public class TimesheetBatch implements Database.Batchable<sObject> {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id, Timesheets_created_till__c, Start_date__c, End_date__c, Placement__c.Approver_timesheets__c,'
            + ' Name, Timesheet_date_notation__c, Timesheet_size__c, Expected_end_date__c, Cost_center__c,'
            + ' Professional__c, Professional__r.User__c, Account__r.Standard_rate_percentage__c, Account__r.Name'
            + ' FROM Placement__c'
            + ' WHERE Create_timesheet__c = true'
        );
    }

    public void execute(Database.BatchableContext bc, List<Placement__c> scope) {
        Map<Id, Placement__c> placementIds = new Map<Id, Placement__c>(scope);

        System.debug('placementIds');
        System.debug(placementIds);

        TimesheetCreator creator = new TimesheetCreator();
        creator.createTimesheets(placementIds);
    }


    public void finish(Database.BatchableContext bc) {
    }
}