force-app/main/default/objects/Placement__c/Placement__c.object-meta.xml
<CustomObject>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Placement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Placements</relationshipLabel>
    <relationshipName>Account_for_placements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement_rate_percentage__c/Placement_rate_percentage__c.object-meta.xml
<CustomObject>
    <label>Placement rate percentage</label>
    <nameField>
        <label>Placement rate percentage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement rate percentages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Placement_rate_percentage__c/fields/Placement__c.field-meta.xml
<CustomField>
    <fullName>Placement__c</fullName>
    <label>Placement</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Placement rate percentages</relationshipLabel>
    <relationshipName>Placement_rate_percentages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Placement_rate_percentage__c/fields/Rate_percentage__c.field-meta.xml
<CustomField>
    <fullName>Rate_percentage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate percentage</label>
    <referenceTo>Rate_percentage__c</referenceTo>
    <relationshipLabel>Placement rate percentages</relationshipLabel>
    <relationshipName>Placement_rate_percentages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rate_percentage__c/Rate_percentage__c.object-meta.xml
<CustomObject>
    <label>Rate percentage</label>
    <nameField>
        <label>Rate percentage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate percentages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate_percentage__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rate percentages</relationshipLabel>
    <relationshipName>Rate_percentages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rate_percentage__c/fields/Is_standard__c.field-meta.xml
<CustomField>
    <fullName>Is_standard__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is standard</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RatePercentageSelectorController.cls
public class RatePercentageSelectorController {
  
    @AuraEnabled(cacheable=true)
    public static RatePercentageWrapper getRatePercentages(Id recordId){
        Placement__c placement = [SELECT Id, Account__c FROM Placement__c WHERE Id = :recordId];

        List<Placement_rate_percentage__c> placementRatePercentages = [SELECT Id, Name, Rate_Percentage__c, Rate_Percentage__r.Is_standard__c  
                                                                        FROM Placement_Rate_Percentage__c 
                                                                        WHERE Placement__c = :recordId];
        List<Rate_Percentage__c> ratePercentages = [SELECT Id, Name FROM Rate_Percentage__c WHERE Account__c = :placement.Account__c];
        
        RatePercentageWrapper wrapper = new RatePercentageWrapper();
        wrapper.selectedRatePercentageList = placementRatePercentages;
        wrapper.notSelectedRatePercentageList = ratePercentages;

        return wrapper;
    }

    @AuraEnabled
    public static string saveRatePercentages(List<String> ratePercentageIds, String recordId){
        List<Placement_rate_percentage__c> placementRatePercentages = [SELECT Id, Rate_percentage__c 
                                                                        FROM Placement_Rate_Percentage__c 
                                                                        WHERE Placement__c = :recordId];
        delete placementRatePercentages;

        Map<Id, Rate_percentage__c> ratePercentagesById = new Map<Id, Rate_percentage__c>([SELECT Id, Name, Account__c FROM Rate_percentage__c WHERE Id IN :ratePercentageIds]);

        List<Placement_rate_percentage__c> prpToInsert = new List<Placement_rate_percentage__c>();
        for(String ratePercentageId : ratePercentageIds){
            Placement_rate_percentage__c newPRP = new Placement_rate_percentage__c();
            newPRP.Name = ratePercentagesById.get(ratePercentageId).Name;
            newPRP.Placement__c = recordId;
            newPRP.Rate_percentage__c = ratePercentageId;
            prpToInsert.add(newPRP);
        }
        if(prpToInsert.size() > 0){
            insert prpToInsert;
        }
        return 'success';
    }
    public class RatePercentageWrapper{
        @AuraEnabled public List<Placement_rate_percentage__c> selectedRatePercentageList {get;set;}
        @AuraEnabled public List<Rate_Percentage__c> notSelectedRatePercentageList {get;set;}
    }
}