force-app/main/default/objects/Placement__c/Placement__c.object-meta.xml
<CustomObject>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Placement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Placements</relationshipLabel>
    <relationshipName>Account_for_placements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Approver_timesheets__c.field-meta.xml
<CustomField>
    <fullName>Approver_timesheets__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver timesheets</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Placements (Approver timesheets)</relationshipLabel>
    <relationshipName>Timesheets_approver</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Expected_end_date__c.field-meta.xml
<CustomField>
    <fullName>Expected_end_date__c</fullName>
    <label>Expected end date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Professional__c.field-meta.xml
<CustomField>
    <fullName>Professional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Professional</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Placements</relationshipLabel>
    <relationshipName>Placements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Timesheet_date_notation__c.field-meta.xml
<CustomField>
    <fullName>Timesheet_date_notation__c</fullName>
    <label>Timesheet date notation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Timesheet_date_notation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Timesheet_size__c.field-meta.xml
<CustomField>
    <fullName>Timesheet_size__c</fullName>
    <label>Timesheet size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Timesheets_created_till__c.field-meta.xml
<CustomField>
    <fullName>Timesheets_created_till__c</fullName>
    <label>Timesheets created till</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <label>Timesheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet__c/fields/End_date__c.field-meta.xml
<CustomField>
    <fullName>End_date__c</fullName>
    <description>INCLUDING this date</description>
    <label>End date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Placement__c.field-meta.xml
<CustomField>
    <fullName>Placement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Placement</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Professional__c.field-meta.xml
<CustomField>
    <fullName>Professional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Professional</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timesheet_entry__c/Timesheet_entry__c.object-meta.xml
<CustomObject>
    <label>Timesheet entry</label>
    <nameField>
        <label>Timesheet entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timesheet entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet_entry__c/fields/Timesheet__c.field-meta.xml
<CustomField>
    <fullName>Timesheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Timesheet</label>
    <referenceTo>Timesheet__c</referenceTo>
    <relationshipLabel>Timesheet entries</relationshipLabel>
    <relationshipName>Timesheet_entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TimesheetCreatorTest.cls
@istest
public class TimesheetCreatorTest {

    @istest
    public static void testCreateTimesheet(){
        Account acc = TestDataFactory.getAccount();
		insert acc;
	
		Contact c = TestDataFactory.getContact();
		c.AccountId = acc.Id;
		insert c;
        
        User u = TestDataFactory.getPortalUser(acc, c);
		insert u;

        c.User__c = u.Id;
        update c;

        Placement__c placement = TestDataFactory.getPlacement();
		placement.Professional__c = c.Id;
        placement.Start_Date__c = Date.newInstance(2024, 01, 25);
        placement.Expected_end_date__c = placement.Start_Date__c.addDays(60);
        placement.Timesheet_date_notation__c = 'Days';
        placement.Timesheet_size__c = 28;
		insert placement;

        Test.startTest();

        TimesheetCreator creator =  new TimesheetCreator();
        creator.createTimesheets(new Map<Id, Placement__c>([
            SELECT
                Id, Timesheets_created_till__c, Start_date__c, End_date__c,
                Name, Timesheet_date_notation__c, Timesheet_size__c, Expected_end_date__c, Cost_center__c, Approver_timesheets__c,
                Professional__c, Professional__r.User__c, Account__r.Standard_rate_percentage__c, Account__r.Name
            FROM
                Placement__c
        ]));
        
        Test.stopTest();

        List<Timesheet__c> timesheets = [SELECT Id, Placement__c, OwnerId FROM Timesheet__c WHERE Placement__c = :placement.Id];
        List<Timesheet_Entry__c> entries = [SELECT Id FROM Timesheet_Entry__c WHERE Timesheet__c = :timesheets[0].Id];

        Assert.areEqual(4, timesheets.size());
        Assert.areEqual(4, entries.size());
    }
}