force-app/main/default/objects/Dataweave_key_mapping__mdt/Dataweave_key_mapping__mdt.object-meta.xml
<CustomObject>
    <description>Contains key/value pair for mapping responses to Apex, associated with key mapping</description>
    <label>Dataweave key mapping</label>
    <pluralLabel>Dataweave key mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Dataweave_key_mapping__mdt/fields/Dataweave_mapping__c.field-meta.xml
<CustomField>
    <fullName>Dataweave_mapping__c</fullName>
    <label>Dataweave mapping</label>
    <referenceTo>Dataweave_mapping__mdt</referenceTo>
    <relationshipLabel>Dataweave key mappings</relationshipLabel>
    <relationshipName>Dataweave_key_mappings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Dataweave_key_mapping__mdt/fields/Incoming_key__c.field-meta.xml
<CustomField>
    <fullName>Incoming_key__c</fullName>
    <label>Incoming key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataweave_key_mapping__mdt/fields/Outgoing_key__c.field-meta.xml
<CustomField>
    <fullName>Outgoing_key__c</fullName>
    <label>Outgoing key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataweave_mapping__mdt/Dataweave_mapping__mdt.object-meta.xml
<CustomObject>
    <description>Object specifying a key mapping, key/value pairs are associated with it to form the mapping</description>
    <label>Dataweave mapping</label>
    <pluralLabel>Dataweave mapping</pluralLabel>
</CustomObject>

force-app/main/default/classes/TranslateJsonToObjects.cls
public with sharing class TranslateJsonToObjects {
    // payload can be any json string
    private String payload;
    // keyMap is a JSON formatted key:value map where the left side is the name of the
    // key in the payload object, and the right side is the name of the key in
    // the returning json.
    private String keyMap;

    public TranslateJsonToObjects(String payload, String keyMap) {
        this.payload = payload;
        this.keyMap = keyMap;
    }

    public TranslateJsonToObjects(
        String payload,
        Dataweave_Mapping__mdt dataweaveMappingMDTRecord
    ) {
        this(
            payload,
            fetchMappingFromCustomMetadata(dataweaveMappingMDTRecord)
        );
    }

    public String translate() {
        Map<String, Object> parameters = new Map<String, Object>();
        parameters.put('mapping', keyMap);
        parameters.put('payload', payload);
        DataWeave.Script script = new DataWeaveScriptResource.translateJson();
        DataWeave.Result result = script.execute(parameters);
        return result.getValueAsString();
    }

    public List<sObject> translateToSObjects(String sObjectType) {
        Type dynamicListType = Type.forName('List<' + sObjectType + '>');
        return (List<sObject>) JSON.deserialize(translate(), dynamicListType);
    }

    public static String fetchMappingFromCustomMetadata(
        Dataweave_Mapping__mdt dataweaveMappingMDT,
        Boolean reverse
    ) {
        List<Dataweave_Key_Mapping__mdt> mappings = [
            SELECT incoming_key__c, outgoing_key__c
            FROM Dataweave_key_mapping__mdt
            WHERE Dataweave_mapping__c = :dataweaveMappingMDT.id
        ];
        Map<String, String> results = new Map<String, String>();

        // TODO: unhack this crap

        for (Dataweave_key_mapping__mdt mapping : mappings) {
            if (reverse) {
                results.put(mapping.outgoing_key__c, mapping.incoming_key__c);

            }
            else {
                results.put(mapping.incoming_key__c, mapping.outgoing_key__c);
            }
        }
        // Should mock a response

        return JSON.serialize(results);
    }

    public static String fetchMappingFromCustomMetadata(
        Dataweave_Mapping__mdt dataweaveMappingMDT) {
        return fetchMappingFromCustomMetadata(dataweaveMappingMDT, false);
    }
}