force-app/main/default/objects/Account_datatable_general_settings__mdt/Account_datatable_general_settings__mdt.object-meta.xml
<CustomObject>
    <description>Contains information on whether to show pagination, add cv column etc</description>
    <label>Account datatable general settings</label>
    <pluralLabel>Account datatable general settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Account_datatable_general_settings__mdt/fields/Account_name__c.field-meta.xml
<CustomField>
    <fullName>Account_name__c</fullName>
    <label>Account name</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_datatable_general_settings__mdt/fields/Id_column__c.field-meta.xml
<CustomField>
    <fullName>Id_column__c</fullName>
    <description>Column that determines the key-field values for the lightning-datatable. Only use this field if you want the column visible, otherwise just specify the api field name in the appropriate field.</description>
    <inlineHelpText>Column that determines the key-field values for the lightning-datatable. Only use this field if you want the column visible, otherwise just specify the api field name in the appropriate field.</inlineHelpText>
    <label>Id column settings</label>
    <referenceTo>Account_datatable_settings__mdt</referenceTo>
    <relationshipLabel>Account datatable general settings</relationshipLabel>
    <relationshipName>Account_datatable_general_settings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Account_datatable_general_settings__mdt/fields/Id_column_api_field_name__c.field-meta.xml
<CustomField>
    <fullName>Id_column_api_field_name__c</fullName>
    <inlineHelpText>Use this field to specify the key-field column if it is NOT visible. Otherwise, use the lookup field.</inlineHelpText>
    <label>Id column api field name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_datatable_settings__mdt/Account_datatable_settings__mdt.object-meta.xml
<CustomObject>
    <description>Contains all information to dynamically build the work component per client (columns to show, column order, type, sortable or not etc)</description>
    <label>Account datatable settings</label>
    <pluralLabel>Account datatable settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Account_datatable_settings__mdt/fields/Account_name__c.field-meta.xml
<CustomField>
    <fullName>Account_name__c</fullName>
    <label>Account name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_datatable_settings__mdt/fields/Api_field_name__c.field-meta.xml
<CustomField>
    <fullName>Api_field_name__c</fullName>
    <description>Contains full API name of field (aka. Application__c.Contact__r.Name)</description>
    <inlineHelpText>Supply full API name of field for which you want the values to show in this columns (ex: Application__c.Contact__r.Name)</inlineHelpText>
    <label>Api field name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SessionConfigurationTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class SessionConfigurationTest {

    @isTest
    static void testAccountName() {
        User u = TestDataFactory.getUser();
        insert u;
        System.runAs(u) {
            String accName = [ SELECT Account_name__c FROM User WHERE Id = :UserInfo.getUserId() ][0].Account_name__c;

            System.assert(SessionConfiguration.accountName == accName);
        }
    }
    @isTest
    static void testAccountId() {
        User u = TestDataFactory.getUser();
        insert u;
        System.runAs(u) {
            Id accId = [SELECT AccountId__c FROM User WHERE Id = :UserInfo.getUserId()][0].AccountId__c;

            System.assert(SessionConfiguration.accountId == accId);
        }
    }

    @isTest
    static void testDatatableConfig() {
        User u = TestDataFactory.getUser();
        insert u;

        System.runAs(u) {
            List<Account_datatable_settings__mdt> conf = SessionConfiguration.workComponentConfig;
            System.assert(conf != null && conf.size() > 0);
        }
    }

    @isTest
    static void testDatatableSettings() {
        User u = TestDataFactory.getUser();
        insert u;

        System.runAs(u) {
            Account_datatable_general_settings__mdt conf = SessionConfiguration.workComponentSettings;
            System.assert(conf != null && !(String.isBlank(conf.Id_column__r.Api_field_name__c) && String.isBlank(conf.Id_column_api_field_name__c)));
        }
    }

    @isTest
    static void testOrgUrl() {
        User u = TestDataFactory.getUser();
        insert u;

        System.runAs(u) {
            System.assertEquals(URL.getOrgDomainUrl().toExternalForm(), SessionConfiguration.orgUrl);
        }
    }
}