force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Candidate_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Professional__c.field-meta.xml
<CustomField>
    <fullName>Professional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field is filled if we got to the stage where a placement was requested and the vendor provided additional information</description>
    <inlineHelpText>Field is filled if we got to the stage where a placement was requested and the vendor provided additional information</inlineHelpText>
    <label>Professional</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications (Professional)</relationshipLabel>
    <relationshipName>Professional_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Preposition__c.field-meta.xml
<CustomField>
    <fullName>Preposition__c</fullName>
    <label>Preposition</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ApplicationFunctions.cls
public with sharing class ApplicationFunctions {
    public static Id createProfessional(Id applicationId, String email, String phone) {
        Application__c app = [
            SELECT Candidate__r.First_name__c, Candidate__r.Last_name__c, Candidate__r.Preposition__c
            FROM Application__c
            WHERE Id = :applicationId
        ];

        Contact professional = new Contact();

        professional.FirstName = app.Candidate__r.First_name__c;
        professional.LastName = String.isNotBlank(app.Candidate__r.Preposition__c) ? (app.Candidate__r.Preposition__c + ' ' + app.Candidate__r.Last_name__c) : app.Candidate__r.Last_name__c;
        professional.Phone = phone;
        professional.Email = email;
        professional.RecordTypeId = SchemaUtils.getRecordTypeId('Contact', 'Professional');
        professional.accountId = [SELECT Id FROM Account WHERE Name = 'Hero Interim Professionals' LIMIT 1].Id;

        insert professional;

        // Update application to reflect professional creation
        app = new Application__c();
        app.Id = applicationId;
        app.Professional__c = professional.Id;

        update app;

        return professional.Id;
    }

    // public class ProfessionalCreationWrapper {
    //     @InvocableVariable(required=true) public String phone;
    //     @InvocableVariable(required=true) public String email;
    //     @InvocableVariable(required=true) public Id applicationId;
    // }

    // @InvocableMethod(label = 'Create professional')
    // public static void createProfessional(List<ProfessionalCreationWrapper> wrappers) {
    //     createProfessional(wrappers[0].applicationId, wrappers[0].email, wrappers[0].phone);
    // }
}