force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Account_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Available_from__c.field-meta.xml
<CustomField>
    <fullName>Available_from__c</fullName>
    <label>Available from</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Candidate_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Holds contact information for specific user at the vendor that manages this application.</description>
    <inlineHelpText>Holds contact information for specific user at the vendor that manages this application.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Desired_rate__c.field-meta.xml
<CustomField>
    <fullName>Desired_rate__c</fullName>
    <label>Desired rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Hours_available__c.field-meta.xml
<CustomField>
    <fullName>Hours_available__c</fullName>
    <inlineHelpText>Hours candidate is available to work per week</inlineHelpText>
    <label>Hours available</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Placement__c.field-meta.xml
<CustomField>
    <fullName>Placement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Placement</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Position_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Professional__c.field-meta.xml
<CustomField>
    <fullName>Professional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field is filled if we got to the stage where a placement was requested and the vendor provided additional information</description>
    <inlineHelpText>Field is filled if we got to the stage where a placement was requested and the vendor provided additional information</inlineHelpText>
    <label>Professional</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications (Professional)</relationshipLabel>
    <relationshipName>Professional_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications (Vendor)</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Account_for_candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Candidates (Vendor)</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Default_vendor_contact__c/Default_vendor_contact__c.object-meta.xml
<CustomObject>
    <description>Connector between a Vendor and corresponding unique contact that&apos;s the &quot;default&quot; contact</description>
    <label>Default vendor contact</label>
    <nameField>
        <label>Default contact for vendor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Default vendor contact</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Default_vendor_contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Default vendor contact</relationshipLabel>
    <relationshipName>Default_vendor_contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Default_vendor_contact__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Default vendor contact</relationshipLabel>
    <relationshipName>Default_vendor_contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement__c/Placement__c.object-meta.xml
<CustomObject>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Placement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Placements</relationshipLabel>
    <relationshipName>Account_for_placements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Placements</relationshipLabel>
    <relationshipName>Application_for_placements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Approver_timesheets__c.field-meta.xml
<CustomField>
    <fullName>Approver_timesheets__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver timesheets</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Placements (Approver timesheets)</relationshipLabel>
    <relationshipName>Timesheets_approver</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Current_rate__c.field-meta.xml
<CustomField>
    <fullName>Current_rate__c</fullName>
    <label>Current rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Expected_end_date__c.field-meta.xml
<CustomField>
    <fullName>Expected_end_date__c</fullName>
    <label>Expected end date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Hiring_manager__c.field-meta.xml
<CustomField>
    <fullName>Hiring_manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Placements (Hiring manager)</relationshipLabel>
    <relationshipName>Hiring_manager_for_placements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Hours_per_week__c.field-meta.xml
<CustomField>
    <fullName>Hours_per_week__c</fullName>
    <label>Hours per week</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Initial_end_date__c.field-meta.xml
<CustomField>
    <fullName>Initial_end_date__c</fullName>
    <label>Initial end date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Placements</relationshipLabel>
    <relationshipName>Position_for_placements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Processing_status__c.field-meta.xml
<CustomField>
    <fullName>Processing_status__c</fullName>
    <label>Processing status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In review by hiring desk</fullName>
            </value>
            <value>
                <fullName>Sent for contracting</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Professional__c.field-meta.xml
<CustomField>
    <fullName>Professional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Professional</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Placements</relationshipLabel>
    <relationshipName>Placements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Timesheet_date_notation__c.field-meta.xml
<CustomField>
    <fullName>Timesheet_date_notation__c</fullName>
    <label>Timesheet date notation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Timesheet_date_notation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Timesheet_size__c.field-meta.xml
<CustomField>
    <fullName>Timesheet_size__c</fullName>
    <label>Timesheet size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Placements (Vendor)</relationshipLabel>
    <relationshipName>Placements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Function title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Account_for_positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Hiring_manager__c.field-meta.xml
<CustomField>
    <fullName>Hiring_manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Positions (Hiring manager)</relationshipLabel>
    <relationshipName>Hiring_manager_for_positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Positions (Position)</relationshipLabel>
    <relationshipName>Positions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Processing_status__c.field-meta.xml
<CustomField>
    <fullName>Processing_status__c</fullName>
    <label>Processing status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Distributed</fullName>
            </value>
            <value>
                <fullName>Candidates offered and in review of manager</fullName>
            </value>
            <value>
                <fullName>Interviews planned</fullName>
            </value>
            <value>
                <fullName>Placement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PlacementFunctions.cls
public without sharing class PlacementFunctions {
    public class PlacementException extends Exception {}
    
    private static void approveInitialApprovalRequest(Id recordId) {
        List<ProcessInstanceWorkItem> piwis = ApprovalController.getPendingApprovalRequestsWithTargetId(recordId);

        if (piwis == null || piwis.size() == 0) {
            throw new PlacementException('Could not find pending approval request for application with id ' + recordId);
        }
        if (piwis.size() > 1) {
            throw new PlacementException('Found multiple pending approval requests for application with id ' + recordId);
        }

        ApprovalController.approveApprovalRequest(piwis[0].Id);
    }

    private static Id getDefaultVendorContact(Id recordId) {
        List<Default_vendor_contact__c> dvcs = [
            SELECT Contact__c 
            FROM Default_vendor_contact__c 
            WHERE Vendor__c 
            IN (SELECT Vendor__c FROM Application__c WHERE Id = :recordId)];

        if (dvcs == null || dvcs.size() == 0) {
            throw new PlacementException('Could not find default vendor contact associated with application ' + recordId);
        }
        if (dvcs.size() > 1) {
            throw new PlacementException('Found multiple default vendor contacts for placement with application ' + recordId);
        }
        return dvcs[0].Contact__c;
    }

    private static void createTaskVendor(Id recordId, Id userId) {
        TaskHandler.TaskWrapper tw = new TaskHandler.TaskWrapper(
            'vendor_provide_professional_information',
            recordId,
            userId,
            Date.today() + 3
        );

        TaskHandler.createTask(tw);
    }

    /* This function advanced the new_placement approval process by one step, 
    from the hiring desk to the vendor for additional information. */
    @AuraEnabled
    public static void handlePlacementRequestInformation(Id recordId) {
        if (String.isBlank(recordId)) {
            return ;
        }

        try {
            // Get default vendor contact
            Id contactId = getDefaultVendorContact(recordId);
            
            approveInitialApprovalRequest(recordId);
            createTaskVendor(recordId, SchemaUtils.getUserFromContactId(contactId));
        }
        catch (Exception e) {
            AuraHandledException err = new AuraHandledException(e.getMessage());
            throw err;
        }
    }

    // private static void approveApprovalRequestHiringDesk(Id recordId) {
    //     List<ProcessInstanceWorkItem> piwis = ApprovalController.getPendingApprovalRequestsWithTargetId(recordId);

    //     if (piwis == null || piwis.size() == 0) {
    //         throw new PlacementException('Could not find pending approval request for placement with id ' + recordId);
    //     }
    //     if (piwis.size() > 1) {
    //         throw new PlacementException('Found multiple pending approval requests for placement with id ' + recordId);
    //     }

    //     ApprovalController.approveApprovalRequest(piwis[0].Id);
    // }

    private static Account getAccount(Id accountId) {
        return [SELECT Id, Standard_timesheet_date_notation__c, Standard_timesheet_size__c FROM Account WHERE Id = :accountId LIMIT 1];
    }

    private static Position__c getPosition(Id positionId) {

        return [
            SELECT Id, Name, Hiring_manager__c, End_date__c
            FROM Position__c
            WHERE Id = :positionId
            LIMIT 1
        ];
    }

    private static Application__c getApplication(Id applicationId) {
        return [
            SELECT Id, Name, Account__c, Position__c, Vendor__c, Professional__c, Candidate__c, Desired_rate__c, Available_from__c, Hours_available__c
            FROM Application__c 
            WHERE Id = :applicationId 
            LIMIT 1
        ];
    }

    @AuraEnabled
    public static Id createPlacement(Id applicationId) {
        try {
            Application__c app = getApplication(applicationId);

            // If there is no professional, we're dealing with a preferential candidate with no intervention from a vendor, 
            // therefor we have to create a professional from the contact info provided by the hiring manager
            if (String.isBlank(app.Professional__c)) {
                Candidate__c cand = [SELECT Email__c, Phone__c FROM Candidate__c WHERE Id = :app.Candidate__c];
                if (String.isBlank(cand.Email__c) || String.isBlank(cand.Phone__c)) {
                    throw new PlacementException(System.Label.lbl_contact_info_needed);
                }
                app.Professional__c = ApplicationFunctions.createProfessional(applicationId, cand.Email__c, cand.Phone__c);
                update app;
            }

            Account acc = getAccount(app.Account__c);
            Position__c pos = getPosition(app.Position__c);

            Placement__c placement = new Placement__c();

            placement.Account__c = acc.Id;
            placement.Application__c = applicationId;
            placement.Approver_timesheets__c = pos.Hiring_manager__c;
            placement.Current_rate__c = app.Desired_rate__c;
            placement.Expected_end_date__c = pos.End_date__c;
            placement.End_date__c = pos.End_date__c;
            placement.Hiring_manager__c = pos.Hiring_manager__c;
            placement.Hours_per_week__c = app.Hours_available__c;
            placement.Initial_end_date__c = placement.Expected_end_date__c;
            placement.Name = pos.Name + ' - ' + app.Name;
            placement.Position__c = pos.Id;
            placement.Processing_status__c = 'New';
            placement.Status__c = 'New';
            placement.Professional__c = app.Professional__c;
            placement.Start_date__c = app.Available_from__c;
            placement.Timesheet_date_notation__c = acc.Standard_timesheet_date_notation__c;
            placement.Timesheet_size__c = acc.Standard_timesheet_size__c;
            placement.Vendor__c = app.Vendor__c;

            insert placement;

            app.Placement__c = placement.Id;
            return placement.Id;
        }
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public static Contact getProfessional(Id placementId) {
        return [
            SELECT Id, FirstName, LastName, Phone, Email 
            FROM Contact 
            WHERE Id IN (
                SELECT Professional__c 
                FROM Placement__c 
                WHERE Id = :placementId) 
            LIMIT 1];
    }

    @AuraEnabled
    public static void sendPlacementForContracting(Id recordId) {
        HeroSalesforceConnector.executeCreate(recordId);

        // Create user associated with contact
        Contact prof = getProfessional(recordId);
        System.enqueueJob(new QueueableController('createUser', new Map<String, Object>{
            'contact' => prof
        }));

        // approveApprovalRequestHiringDesk(recordId);
    }
}