force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Account_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Candidate_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Position_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Reason_rejection_hiring_desk__c.field-meta.xml
<CustomField>
    <fullName>Reason_rejection_hiring_desk__c</fullName>
    <description>Reason for rejection by hiring desk</description>
    <label>Reason for rejection</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Reason_rejection_hiring_desk</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Send_to_hiring_manager__c.field-meta.xml
<CustomField>
    <fullName>Send_to_hiring_manager__c</fullName>
    <description>Internal field for hiring desk to keep track of applicants they like or dislike</description>
    <inlineHelpText>Indicate whether you intend to send an applicant to the next stage. For internal use only.</inlineHelpText>
    <label>Send to hiring manager</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intake requested</fullName>
            </value>
            <value>
                <fullName>Intake planned</fullName>
            </value>
            <value>
                <fullName>Intake done</fullName>
            </value>
            <value>
                <fullName>Position offered</fullName>
            </value>
            <value>
                <fullName>Position not offered</fullName>
            </value>
            <value>
                <fullName>Placement</fullName>
            </value>
            <value>
                <fullName>Position not accepted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Sent to hiring manager</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Candidate withdrawn</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Placement requested</fullName>
            </value>
            <value>
                <fullName>Information requested for placement</fullName>
            </value>
            <value>
                <fullName>Invited for intake</fullName>
                <isActive>false</isActive>
                <label>Invited for intake</label>
            </value>
            <value>
                <fullName>Rejected by hiring manager</fullName>
                <isActive>false</isActive>
                <label>Rejected by hiring manager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/recordTypes/Aspen.recordType-meta.xml
<RecordType>
    <fullName>Aspen</fullName>
    <active>true</active>
    <label>Aspen</label>
</RecordType>

force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Account_for_candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate__c/recordTypes/Aspen.recordType-meta.xml
<RecordType>
    <fullName>Aspen</fullName>
    <active>true</active>
    <label>Aspen</label>
</RecordType>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Function title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Account_for_positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Max_number_of_applicants_per_supplier__c.field-meta.xml
<CustomField>
    <fullName>Max_number_of_applicants_per_supplier__c</fullName>
    <label>Max number of applicants per supplier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Positions (Position)</relationshipLabel>
    <relationshipName>Positions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Afgewezen</label>
            </value>
            <value>
                <fullName>Concept</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Applications with hiring manager</fullName>
                <isActive>false</isActive>
                <label>Applications with hiring manager</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Sent to hiring manager</fullName>
                <isActive>false</isActive>
                <label>Sent to hiring manager</label>
            </value>
            <value>
                <fullName>Unapproved</fullName>
                <isActive>false</isActive>
                <label>Unapproved</label>
            </value>
            <value>
                <fullName>Up for correction</fullName>
                <isActive>false</isActive>
                <label>Up for correction</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/recordTypes/Aspen.recordType-meta.xml
<RecordType>
    <fullName>Aspen</fullName>
    <active>true</active>
    <label>Aspen</label>
</RecordType>

force-app/main/default/objects/Vendor_position_application__c/Vendor_position_application__c.object-meta.xml
<CustomObject>
    <description>Object used to store information about applications on a position per vendor, such as number of applications a vendor has made on a position.</description>
    <label>Vendor position application</label>
    <nameField>
        <label>Vendor position application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor position applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_position_application__c/fields/Number_of_active_applications__c.field-meta.xml
<CustomField>
    <fullName>Number_of_active_applications__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of active applications</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vendor_position_application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Vendor position applications</relationshipLabel>
    <relationshipName>Vendor_position_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ApplicationTriggerHandlerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class ApplicationTriggerHandlerTest {
    // @isTest
    // static void testCreateTask() {
    //     Account a = TestDataFactory.getAccount();
    //     a.Hiring_desk_queue_id__c = SchemaUtils.getQueueIdFromName('Aspen hiring desk');
    //     a.Hiring_desk_group_id__c = SchemaUtils.getGroupByName('Hero hiring desk');

    //     insert a;

    //     Contact c = TestDataFactory.getContact('Bob', 'Inhuur', a);

    //     insert c;

    //     Position__c p = TestDataFactory.getPosition(false);
    //     p.Account__c = a.Id;

    //     insert p;

    //     Candidate__c cand = new Candidate__c();
	// 	cand.First_name__c = 'Bob';
	// 	cand.Last_name__c = 'Bob';

	// 	insert cand;

    //     Application__c app = new Application__c();

	// 	app.Account__c = a.Id;
	// 	app.Position__c = p.Id;
	// 	app.Candidate__c = cand.Id;
    //     app.Status__c = 'Placement requested';

    //     insert app;

    //     // System.debug('POSITION TEST: ' + [SELECT Account__r.Hiring_desk_group_id__c FROM Position__c WHERE Id = :p.Id]);

    //     // Account v = TestDataFactory.getVendor();

    //     // Application__c app = new//TestDataFactory.getApplication(p.Id, a.Id);

    //     // app.Status__c = 'Placement requested';

    //     // insert app;

    //     List<Task> createdTask = [SELECT Id, Subject, OwnerId FROM Task ORDER BY CreatedDate DESC];

    //     Set<Id> ownerIds = DeveloperUtils.getIdFieldSet(createdTask, 'ownerId');
    //     System.assert(ownerIds.contains(a.Hiring_desk_queue_id__c));
    // }

    @isTest
    static void testNameFormat() {
        Account a = TestDataFactory.getAccount();
        a.Hiring_desk_group_id__c = SchemaUtils.getGroupByName('Hero hiring desk');
        
        insert a;

        Position__c p = TestDataFactory.getPosition(false);

        p.Account__c = a.Id;

        insert p;

        Account v = TestDataFactory.getVendor();

        insert v;

        Application__c app = TestDataFactory.getApplication('Bee', 'Worker', p, v);

        System.assert(TestUtils.nameAdded(app, 'Application__c', 'Bee Worker'));
    }

    @isTest
    static void checkEmptyRejectionReason() {
        Account a = TestDataFactory.getAccount();
        a.Hiring_desk_group_id__c = SchemaUtils.getGroupByName('Hero hiring desk');
        
        insert a;

        Contact c = TestDataFactory.getContact('Bob', 'Vendor', a);

        insert c;

        User Owner = TestDataFactory.getPortalUser(a, c);

        insert Owner;

        User hiringDesk = TestDataFactory.getUserNoAccount();

        insert hiringDesk;

        Position__c p = TestDataFactory.getPosition(false);

        p.Account__c = a.Id;

        insert p;

        Account v = TestDataFactory.getVendor();

        insert v;

        Application__c app = TestDataFactory.getApplication('Fn_', 'Ln_', p, v);

        app.Send_to_hiring_manager__c = 'No';
        app.Reason_rejection_hiring_desk__c = 'Distance';

        insert app;

        Test.startTest();

        app.Send_to_hiring_manager__c = 'Yes';

        update app;

        Test.stopTest();

        Application__c res = [SELECT Reason_rejection_hiring_desk__c FROM Application__c WHERE Id = :app.Id LIMIT 1];
        System.assertEquals(null, res.Reason_rejection_hiring_desk__c);
    }

    @isTest
    static void testIncreaseNumberApplicationsOffered() {Account a = TestDataFactory.getAccount();
        a.Hiring_desk_group_id__c = SchemaUtils.getGroupByName('Hero hiring desk');
        
        insert a;

        Contact c = TestDataFactory.getContact('Bob', 'Vendor', a);

        insert c;

        User Owner = TestDataFactory.getPortalUser(a, c);

        insert Owner;

        User hiringDesk = TestDataFactory.getUserNoAccount();

        insert hiringDesk;

        Position__c p = TestDataFactory.getPosition(false);

        p.Account__c = a.Id;
        p.Max_number_of_applicants_per_supplier__c = '3';

        insert p;

        Account v = TestDataFactory.getVendor();

        insert v;

        Vendor_position_application__c conn = TestDataFactory.getPositionLinkedToVendor(v, p);

        insert conn;

        Application__c app = TestDataFactory.getApplication('Fn_', 'Ln_', p, v);

        app.Send_to_hiring_manager__c = 'No';
        app.Reason_rejection_hiring_desk__c = 'Distance';

        test.startTest();
        insert app;
        test.stopTest();
        
        conn = [SELECT Number_of_active_applications__c FROM Vendor_position_application__c WHERE Id = :conn.Id LIMIT 1];

        System.assertEquals(1, Integer.valueOf(conn.Number_of_active_applications__c));
    }
}