force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Account_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Approval_status__c.field-meta.xml
<CustomField>
    <fullName>Approval_status__c</fullName>
    <label>Approval status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved by hiring desk</fullName>
            </value>
            <value>
                <fullName>Approved by hiring manager</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected by hiring desk</fullName>
            </value>
            <value>
                <fullName>Rejected by hiring manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Hours_available__c.field-meta.xml
<CustomField>
    <fullName>Hours_available__c</fullName>
    <inlineHelpText>Hours candidate is available to work per week</inlineHelpText>
    <label>Hours available</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Position_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intake requested</fullName>
            </value>
            <value>
                <fullName>Intake planned</fullName>
            </value>
            <value>
                <fullName>Intake done</fullName>
            </value>
            <value>
                <fullName>Position offered</fullName>
            </value>
            <value>
                <fullName>Position not offered</fullName>
            </value>
            <value>
                <fullName>Placement</fullName>
            </value>
            <value>
                <fullName>Position not accepted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Sent to hiring manager</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Candidate withdrawn</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Placement requested</fullName>
            </value>
            <value>
                <fullName>Information requested for placement</fullName>
            </value>
            <value>
                <fullName>Invited for intake</fullName>
                <isActive>false</isActive>
                <label>Invited for intake</label>
            </value>
            <value>
                <fullName>Rejected by hiring manager</fullName>
                <isActive>false</isActive>
                <label>Rejected by hiring manager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications (Vendor)</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Function title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Account_for_positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Approval_status__c.field-meta.xml
<CustomField>
    <fullName>Approval_status__c</fullName>
    <label>Approval status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Application distributed</fullName>
                <isActive>false</isActive>
                <label>Application distributed</label>
            </value>
            <value>
                <fullName>Candidates offered and in review of manager</fullName>
                <isActive>false</isActive>
                <label>Candidates offered and in review of manager</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
            <value>
                <fullName>DEVOPS</fullName>
                <isActive>false</isActive>
                <label>DEVOPS</label>
            </value>
            <value>
                <fullName>Interviews planned</fullName>
                <isActive>false</isActive>
                <label>Interviews planned</label>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
                <isActive>false</isActive>
                <label>Open</label>
            </value>
            <value>
                <fullName>TEST</fullName>
                <isActive>false</isActive>
                <label>TEST</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Positions (Position)</relationshipLabel>
    <relationshipName>Positions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Afgewezen</label>
            </value>
            <value>
                <fullName>Concept</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Applications with hiring manager</fullName>
                <isActive>false</isActive>
                <label>Applications with hiring manager</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Sent to hiring manager</fullName>
                <isActive>false</isActive>
                <label>Sent to hiring manager</label>
            </value>
            <value>
                <fullName>Unapproved</fullName>
                <isActive>false</isActive>
                <label>Unapproved</label>
            </value>
            <value>
                <fullName>Up for correction</fullName>
                <isActive>false</isActive>
                <label>Up for correction</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SchemaUtilsTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class SchemaUtilsTest {

    @isTest
    static void testWildCard() {

        Set<String> res = SchemaUtils.wildcardSelector('Position__c');

        System.assert(res.contains('Name'));
        System.assert(res.contains('Approval_status__c'));
    }

    @isTest
    static void testGetAllFieldNamesExpand() {
        String obj = 'Application__c';
        Map<String, List<String>> relationshipsByObj = new Map<String, List<String>>{
            'Application__c' => new List<String>{'Position__r'},//'Vendor__r'
            'Position__c' => new List<String>{'Account__r'}
            // 'Vendor__c' => new List<String>{'Account__r'}
        };

        Set<String> res = SchemaUtils.getAllFieldNames(obj, relationshipsByObj);

        System.assert(res.contains('Position__r.Account__r.Name'));
        System.assert(res.contains('Position__r.Id'));
        System.assert(res.contains('Position__c'));
    }

    @isTest
    static void testGetAllFieldNames() {
        String obj = 'Application__c';
        List<String> rels = new List<String>{'Position__r'}; // 'Vendor__r'

        Set<String> res = SchemaUtils.getAllFieldNames(obj, rels);

        // System.assert(res.contains('Vendor__r.Email__c'));
        System.assert(res.contains('Position__r.Id'));
        System.assert(res.contains('Position__c'));
    }

    @isTest
    static void testGetFieldType() {
        String objectName = 'Application__c';
        String fieldName = 'Status__c';

        Schema.DisplayType type = SchemaUtils.getFieldType(objectName, fieldName);

        System.assertEquals(Schema.DisplayType.PICKLIST, type);

        fieldName = 'Hours_available__c';
        type = SchemaUtils.getFieldType(objectName, fieldName);

        System.assertEquals(Schema.DisplayType.DOUBLE, type);
    }

    @isTest
    static void testInvalidObject() {
        try {
            Set<String> res = SchemaUtils.getAllFieldNames('Ladieda');
            System.Assert.fail();
        } catch (Exception e) {
            System.assert(e.getTypeName() == 'SchemaUtils.SchemaUtilsException');
        }
    }

    @isTest
    static void testGetRecordTypeId() {
        Id res = SchemaUtils.getRecordTypeId('Contact', 'Professional');

        System.assert(res != null);
    }

    @isTest
    static void testGetRecordTypeName() {
        Id recordTypeId = SchemaUtils.getRecordTypeId('Contact', 'Professional');
        String res = SchemaUtils.getRecordTypeName('Contact', recordTypeId);

        System.assert(res == 'Professional');
    }
}