force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Account_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Candidate_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Hiring_manager_associated_position__c.field-meta.xml
<CustomField>
    <fullName>Hiring_manager_associated_position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring manager associated position</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Position_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intake requested</fullName>
            </value>
            <value>
                <fullName>Intake planned</fullName>
            </value>
            <value>
                <fullName>Intake done</fullName>
            </value>
            <value>
                <fullName>Position offered</fullName>
            </value>
            <value>
                <fullName>Position not offered</fullName>
            </value>
            <value>
                <fullName>Placement</fullName>
            </value>
            <value>
                <fullName>Position not accepted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Sent to hiring manager</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Candidate withdrawn</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Placement requested</fullName>
            </value>
            <value>
                <fullName>Information requested for placement</fullName>
            </value>
            <value>
                <fullName>Invited for intake</fullName>
                <isActive>false</isActive>
                <label>Invited for intake</label>
            </value>
            <value>
                <fullName>Rejected by hiring manager</fullName>
                <isActive>false</isActive>
                <label>Rejected by hiring manager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/recordTypes/Aspen.recordType-meta.xml
<RecordType>
    <fullName>Aspen</fullName>
    <active>true</active>
    <label>Aspen</label>
</RecordType>

force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Account_for_candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate__c/recordTypes/Aspen.recordType-meta.xml
<RecordType>
    <fullName>Aspen</fullName>
    <active>true</active>
    <label>Aspen</label>
</RecordType>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Function title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Account_for_positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Hiring_manager__c.field-meta.xml
<CustomField>
    <fullName>Hiring_manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Positions (Hiring manager)</relationshipLabel>
    <relationshipName>Hiring_manager_for_positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Is_template_position__c.field-meta.xml
<CustomField>
    <fullName>Is_template_position__c</fullName>
    <label>Is template position</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Actual_position</fullName>
                <label>Actual position</label>
            </value>
            <value>
                <fullName>Template_position</fullName>
                <label>Template position</label>
            </value>
            <value>
                <fullName>Concept_position</fullName>
                <label>Concept position</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Positions (Position)</relationshipLabel>
    <relationshipName>Positions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Afgewezen</label>
            </value>
            <value>
                <fullName>Concept</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Applications with hiring manager</fullName>
                <isActive>false</isActive>
                <label>Applications with hiring manager</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Sent to hiring manager</fullName>
                <isActive>false</isActive>
                <label>Sent to hiring manager</label>
            </value>
            <value>
                <fullName>Unapproved</fullName>
                <isActive>false</isActive>
                <label>Unapproved</label>
            </value>
            <value>
                <fullName>Up for correction</fullName>
                <isActive>false</isActive>
                <label>Up for correction</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/recordTypes/Aspen.recordType-meta.xml
<RecordType>
    <fullName>Aspen</fullName>
    <active>true</active>
    <label>Aspen</label>
</RecordType>

force-app/main/default/objects/Timesheet__c/Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <label>Timesheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet__c/fields/Timesheet_approver__c.field-meta.xml
<CustomField>
    <fullName>Timesheet_approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Timesheet approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_to_timesheet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PortalButtonsControllerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class PortalButtonsControllerTest {

    @isTest
    static void testHiringManagerSubmitApprovalVisible() {
        // TO DO: implement unit test
        // Get a hiring manager that is a portal user
        Account a = TestDataFactory.getAccount('Aspen');
        insert a;
        
        Contact c = TestDataFactory.getContact('Hiring', 'Manageeeeeeeeeer', a);
        insert c;
        
        User u = TestDataFactory.getPortalUser(a, c);
        u.Account_name__c = 'Aspen';
        insert u;

        Id recordTypeId = SchemaUtils.getRecordTypeId('Position__c', 'Aspen');
        
        Position__c p = TestDataFactory.getPosition(false);
        p.OwnerId = u.Id;
        p.Status__c = 'New';
        p.Is_template_position__c = 'Actual_position';
        p.RecordTypeId = recordTypeId;
        p.Hiring_manager__c = c.Id;

        insert p;

        System.runAs(u) {
            List<PortalButtonsController.Button> buttons = PortalButtonsController.getButtons(p.Id).buttons;
            for (PortalButtonsController.Button btn: buttons) {
                if (btn.ActionName == 'Submit approval') {
                    System.assert(btn.visible == true);
                }
            }
        }
    }

    @isTest
    static void testHiringManagerSubmitApprovalNotVisibleStatus() {
        // TO DO: implement unit test
        // Get a hiring manager that is a portal user
        Account a = TestDataFactory.getAccount('Aspen');
        insert a;

        Contact c = TestDataFactory.getContact('Hiring', 'Manageeeeeeeeeer', a);
        insert c;
        
        User u = TestDataFactory.getPortalUser(a, c);
        u.Account_name__c = 'Aspen';
        insert u;

        Id recordTypeId = SchemaUtils.getRecordTypeId('Position__c', 'Aspen');
        
        Position__c p = TestDataFactory.getPosition(false);
        p.OwnerId = u.Id;
        p.Status__c = 'Concept';
        p.Is_template_position__c = 'Actual_position';
        p.RecordTypeId = recordTypeId;
        p.Hiring_manager__c = c.Id;

        insert p;

        System.runAs(u) {
            List<PortalButtonsController.Button> buttons = PortalButtonsController.getButtons(p.Id).buttons;
            for (PortalButtonsController.Button btn: buttons) {
                if (btn.ActionName == 'Submit approval') {
                    System.assert(btn.visible == true);
                }
            }
        }
    }

    // @isTest
    // static void testVendorSubmittedApplicationButtons() {
    //     Account a = TestDataFactory.getAccount('Aspen');
    //     a.Hiring_desk_group_id__c = SchemaUtils.getGroupByName('Hero hiring desk');
    //     insert a;
        
    //     Contact c = TestDataFactory.getContact('Ven', 'Dor', a);
    //     insert c;
        
    //     User u = TestDataFactory.getPortalUserVendor(a, c);
    //     u.Account_name__c = 'Aspen';
    //     insert u;

    //     User adm = TestDataFactory.getUserNoAccount();
    //     insert adm;

    //     System.runAs(adm) {
    //         TestDataFactory.addPermissionSetToUser(u, 'Basic_application_process_permissions');
    //     }

    //     Id recordTypeId = SchemaUtils.getRecordTypeId('Application__c', 'Aspen');
        
    //     Candidate__c cand = TestDataFactory.getCandidate('Can', 'Didate');
    //     cand.Account__c = a.Id;
    //     insert cand;

    //     Position__c pos = TestDataFactory.getPosition(false);
    //     pos.Account__c = a.Id;
    //     insert pos;

    //     Application__c app = TestDataFactory.getApplication(cand);
    //     app.Position__c = pos.Id;
    //     insert app;
    //     System.runAs(u) {
    //         List<PortalButtonsController.Button> buttons = PortalButtonsController.getButtons(app.Id);

    //         for (PortalButtonsController.Button btn: buttons) {
    //             if (btn.actionName == 'Recall approval') {
    //                 System.assert(btn.visible == false);
    //             }
    //         }
    //     }
    // }

    @isTest
    static void testHiringManagerApproveTimeSheet() {
        // TO DO: implement unit test
        // Get a hiring manager that is a portal user
        Account a = TestDataFactory.getAccount('Aspen');
        insert a;

        Contact c = TestDataFactory.getContact('Hiring', 'Manageeeeeeeeeer', a);
        insert c;
        
        User u = TestDataFactory.getPortalUser(a, c);
        u.Account_name__c = 'Aspen';
        insert u;

        Timesheet__c t = TestDataFactory.getTimesheet();
        t.Timesheet_approver__c = u.Id;
        t.OwnerId = u.Id;

        insert t;

        System.runAs(u) {
            List<PortalButtonsController.Button> buttons = PortalButtonsController.getButtons(t.Id).buttons;
            for (PortalButtonsController.Button btn: buttons) {
                if (btn.ActionName == 'Approve approval') {
                    System.assert(btn.visible == false);
                }
                if (btn.ActionName == 'Reject approval') {
                    System.assert(btn.visible == false);
                }
            }

            ApprovalController.submitApprovalRequestToUser(t.Id, 'Approve_timesheet', u.Id);

            buttons = PortalButtonsController.getButtons(t.Id).buttons;
            for (PortalButtonsController.Button btn: buttons) {
                if (btn.ActionName == 'Approve approval') {
                    System.assert(btn.visible == true);
                }
                if (btn.ActionName == 'Reject approval') {
                    System.assert(btn.visible == true);
                }
            }
        }
    }

    
    @isTest
    static void testHiringManagerApproveApplication() {
        Account a = TestDataFactory.getAccount('Aspen');
        a.Hiring_desk_group_id__c = SchemaUtils.getGroupByName('Hero hiring desk');
        insert a;

        Contact c = TestDataFactory.getContact('Hiring', 'Manageeeeeeeeeer', a);
        insert c;
        
        User u = TestDataFactory.getPortalUser(a, c);
        u.Account_name__c = 'Aspen';
        insert u;

        Id recordTypeId = SchemaUtils.getRecordTypeId('Application__c', 'Aspen');
        
        Candidate__c cand = TestDataFactory.getCandidate('Can', 'Didate');
        cand.Account__c = a.Id;
        insert cand;

        Position__c pos = TestDataFactory.getPosition(false);
        pos.Account__c = a.Id;
        insert pos;

        Application__c app = TestDataFactory.getApplication(cand);
        app.Position__c = pos.Id;
        app.Hiring_manager_associated_position__c = u.Id;
        app.Account__c = a.Id;
        app.OwnerId = u.Id;
        insert app;
        
        app.Account__c = a.Id;
        update app;

        // ApprovalController.submitApprovalRequest(app.Id);
        List<ProcessInstanceWorkItem> piwis = ApprovalController.getPendingApprovalRequestsWithTargetId(app.Id);
        ApprovalController.processApprovalRequest(new ApprovalController.ApprovalHandlerWrapper(
            piwis[0].Id,
            'Approve', 
            '',
            u.Id
        ));
        System.runAs(u) {
            List<PortalButtonsController.Button>buttons = PortalButtonsController.getButtons(app.Id).buttons;
            for (PortalButtonsController.Button btn: buttons) {
                if (btn.ActionName == 'Plan intake') {
                    System.assert(btn.visible == true);
                }
                if (btn.ActionName == 'Reject approval') {
                    System.assert(btn.visible == true);
                }
            }
        }
    }
}