force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Clarification_hiring_desk__c.field-meta.xml
<CustomField>
    <fullName>Clarification_hiring_desk__c</fullName>
    <description>Hiring desk uses this field to write comments to either hiring manager or vendor based on Send_to_hiring_manager field.</description>
    <inlineHelpText>Provide additional clarification to either vendor or hiring manager about the reasons for advancing or rejecting an application</inlineHelpText>
    <label>Clarification hiring desk</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Holds contact information for specific user at the vendor that manages this application.</description>
    <inlineHelpText>Holds contact information for specific user at the vendor that manages this application.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Position_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Send_to_hiring_manager__c.field-meta.xml
<CustomField>
    <fullName>Send_to_hiring_manager__c</fullName>
    <description>Internal field for hiring desk to keep track of applicants they like or dislike</description>
    <inlineHelpText>Indicate whether you intend to send an applicant to the next stage. For internal use only.</inlineHelpText>
    <label>Send to hiring manager</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intake requested</fullName>
            </value>
            <value>
                <fullName>Intake planned</fullName>
            </value>
            <value>
                <fullName>Intake done</fullName>
            </value>
            <value>
                <fullName>Position offered</fullName>
            </value>
            <value>
                <fullName>Position not offered</fullName>
            </value>
            <value>
                <fullName>Placement</fullName>
            </value>
            <value>
                <fullName>Position not accepted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Sent to hiring manager</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Candidate withdrawn</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Placement requested</fullName>
            </value>
            <value>
                <fullName>Information requested for placement</fullName>
            </value>
            <value>
                <fullName>Invited for intake</fullName>
                <isActive>false</isActive>
                <label>Invited for intake</label>
            </value>
            <value>
                <fullName>Rejected by hiring manager</fullName>
                <isActive>false</isActive>
                <label>Rejected by hiring manager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications (Vendor)</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dataweave_key_mapping__mdt/Dataweave_key_mapping__mdt.object-meta.xml
<CustomObject>
    <description>Contains key/value pair for mapping responses to Apex, associated with key mapping</description>
    <label>Dataweave key mapping</label>
    <pluralLabel>Dataweave key mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Dataweave_key_mapping__mdt/fields/Dataweave_mapping__c.field-meta.xml
<CustomField>
    <fullName>Dataweave_mapping__c</fullName>
    <label>Dataweave mapping</label>
    <referenceTo>Dataweave_mapping__mdt</referenceTo>
    <relationshipLabel>Dataweave key mappings</relationshipLabel>
    <relationshipName>Dataweave_key_mappings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Dataweave_key_mapping__mdt/fields/Incoming_key__c.field-meta.xml
<CustomField>
    <fullName>Incoming_key__c</fullName>
    <label>Incoming key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataweave_key_mapping__mdt/fields/Outgoing_key__c.field-meta.xml
<CustomField>
    <fullName>Outgoing_key__c</fullName>
    <label>Outgoing key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataweave_mapping__mdt/Dataweave_mapping__mdt.object-meta.xml
<CustomObject>
    <description>Object specifying a key mapping, key/value pairs are associated with it to form the mapping</description>
    <label>Dataweave mapping</label>
    <pluralLabel>Dataweave mapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/Default_vendor_contact__c/Default_vendor_contact__c.object-meta.xml
<CustomObject>
    <description>Connector between a Vendor and corresponding unique contact that&apos;s the &quot;default&quot; contact</description>
    <label>Default vendor contact</label>
    <nameField>
        <label>Default contact for vendor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Default vendor contact</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Default_vendor_contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Default vendor contact</relationshipLabel>
    <relationshipName>Default_vendor_contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Default_vendor_contact__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Default vendor contact</relationshipLabel>
    <relationshipName>Default_vendor_contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Function title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Hiring_manager__c.field-meta.xml
<CustomField>
    <fullName>Hiring_manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Positions (Hiring manager)</relationshipLabel>
    <relationshipName>Hiring_manager_for_positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Is_template_position__c.field-meta.xml
<CustomField>
    <fullName>Is_template_position__c</fullName>
    <label>Is template position</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Actual_position</fullName>
                <label>Actual position</label>
            </value>
            <value>
                <fullName>Template_position</fullName>
                <label>Template position</label>
            </value>
            <value>
                <fullName>Concept_position</fullName>
                <label>Concept position</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Positions (Position)</relationshipLabel>
    <relationshipName>Positions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Processing_status__c.field-meta.xml
<CustomField>
    <fullName>Processing_status__c</fullName>
    <label>Processing status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Distributed</fullName>
            </value>
            <value>
                <fullName>Candidates offered and in review of manager</fullName>
            </value>
            <value>
                <fullName>Interviews planned</fullName>
            </value>
            <value>
                <fullName>Placement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Afgewezen</label>
            </value>
            <value>
                <fullName>Concept</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Applications with hiring manager</fullName>
                <isActive>false</isActive>
                <label>Applications with hiring manager</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Sent to hiring manager</fullName>
                <isActive>false</isActive>
                <label>Sent to hiring manager</label>
            </value>
            <value>
                <fullName>Unapproved</fullName>
                <isActive>false</isActive>
                <label>Unapproved</label>
            </value>
            <value>
                <fullName>Up for correction</fullName>
                <isActive>false</isActive>
                <label>Up for correction</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WorkcomponentApplicationsController.cls
public with sharing class WorkcomponentApplicationsController {
    // public class DocumentInfo {
    //     @AuraEnabled public Id cvId;
    //     @AuraEnabled public Id versionId;
    // }
    private static String mappingName = 'Application_to_wrapper';

    public class ApplicationWrapper {
        @AuraEnabled public Id Id;
        @AuraEnabled public String applicationName;
        @AuraEnabled public Boolean isPreferredCandidate;
        @AuraEnabled public Date availableFrom;
        @AuraEnabled public Decimal rate;
        @AuraEnabled public Decimal hoursAvailable;
        @AuraEnabled public Decimal rating;
        @AuraEnabled public String status;
        @AuraEnabled public String comment;
        @AuraEnabled public String rejectionReasonHiringDesk;
        @AuraEnabled public String sendToHiringManager;
        @AuraEnabled public Boolean reasonRejectionEditable;
        @AuraEnabled public String clarification;
        @AuraEnabled public Boolean STD_editable_col;//WorkcomponentSettingsController.STANDARD_EDITABLE_COL_NAME;
 
        /* Position fields */
        // TODO: something about money
        @AuraEnabled public Id positionId;
        @AuraEnabled public String positionName;
        @AuraEnabled public Datetime deadline;
        @AuraEnabled public Id hiringManagerId;
        @AuraEnabled public String hiringManagerName;
 
        /* Candidate fields */
        @AuraEnabled public Id candidateId;
        @AuraEnabled public String candidateName;
 
        /* Contact fields */
        @AuraEnabled public Id contactId;
        @AuraEnabled public String contactName;
        @AuraEnabled public String contactPhone;
        @AuraEnabled public String contactEmail;
 
        /* Vendor fields */
        @AuraEnabled public Id vendorId;
        @AuraEnabled public String vendorName;
 
        /* Other fields */
        @AuraEnabled public Id cvId; // Contains DocumentId AND ContentVersionId
        @AuraEnabled public Id versionId;
        // @AuraEnabled public Id cvVersion;
       
        /* Fuctionality fields */
        @AuraEnabled public Boolean editable;
    }

    public static Map<String, String> fieldNamesByColumnNames {
        get {
            if (fieldNamesByColumnNames == null) {
                fieldNamesByColumnNames = new Map<String, String>();
                Dataweave_mapping__mdt mapper = [SELECT Id, DeveloperName FROM Dataweave_mapping__mdt WHERE DeveloperName = :mappingName LIMIT 1];

                List<Dataweave_Key_Mapping__mdt> mappings = [
                    SELECT incoming_key__c, outgoing_key__c
                    FROM Dataweave_Key_Mapping__mdt
                    WHERE Dataweave_Mapping__r.id = :mapper.id
                ];

                for (Dataweave_key_mapping__mdt mapping : mappings) {
                    fieldNamesByColumnNames.put(mapping.outgoing_key__c, mapping.incoming_key__c);
                }
            }
            return fieldNamesByColumnNames;
        }
        private set;
    }

    public static Map<String, String> columnNamesByFieldNames {
        get {
            if (columnNamesByFieldNames == null) {
                columnNamesByFieldNames = DeveloperUtils.reverseMap(fieldNamesByColumnNames);
            }
            return columnNamesByFieldNames;
        }
        private set;
    }
 
    @AuraEnabled(cacheable=true)
    public static WorkcomponentSettingsController.ComponentConfiguration   getSettings(String componentName) {
        return WorkcomponentSettingsController.getSettings(componentName, columnNamesByFieldNames);
    }
 
    public static WorkcomponentSettingsController.ComponentConfiguration getConfigurationFromJson(String componentJson) {
        if (String.isBlank(componentJson))
            return null;
       
        return (WorkcomponentSettingsController.ComponentConfiguration)JSON.deserialize(componentJson,
            WorkcomponentSettingsController.ComponentConfiguration.class);
    }
 
    private static List<ApplicationWrapper> getApplicationsInner(
        WorkcomponentSettingsController.ComponentConfiguration componentConfiguration,
        WorkComponentDataController controller) {
 
        List<Map<String, Object>> dataMap = controller.getData(componentConfiguration, mappingName);
        List<ApplicationWrapper> data = new List<ApplicationWrapper>();
 
        if (dataMap != null) {
            for (Map<String, Object> objMap: dataMap) {
                data.add((ApplicationWrapper)JSON.deserialize(JSON.serialize(objMap), ApplicationWrapper.class));
            }
        }
 
        return data;
    }
 
    @AuraEnabled(cacheable=true)
    public static List<ApplicationWrapper> getApplicationsProcessable(String componentConfigurationJson,
    String sortCol, String sortOrder, Id recordId) {
        WorkcomponentSettingsController.ComponentConfiguration componentConfiguration = getConfigurationFromJson(componentConfigurationJson);
       
        if (componentConfiguration == null) {
            return null;
        }
        String sortColApiName = fieldNamesByColumnNames.get(sortCol);
       
        // TODO: GET RIGHT FILTERS!! (Email sent, with hiring manager etc)
        List<QueryBuilder.FilterClause> filters = new List<QueryBuilder.FilterClause>();
        filters.add(new QueryBuilder.StringFilterClause('Status__c', 'New'));
        filters.add(new QueryBuilder.StringFilterClause('Position__c', recordId));
        filters.add(new QueryBuilder.StringFilterClause('Send_to_hiring_manager__c', 'Open', true));
 
        System.debug('filters: ' + filters);
        System.debug('sortColApiName: ' + sortColApiName);
        System.debug('sortOrder: ' + sortOrder);
 
        QueryBuilder.OrderClause order = new QueryBuilder.OrderClause(sortColApiName, sortOrder);
 
        WorkComponentDataController controller = new WorkComponentDataController(filters, order);
        return getApplicationsInner(componentConfiguration, controller);
    }
 
    @AuraEnabled(cacheable=true)
    public static List<ApplicationWrapper>    getData(String componentConfigurationJson,
    String sortCol, String sortOrder, Id recordId) {
        WorkcomponentSettingsController.ComponentConfiguration componentConfiguration = getConfigurationFromJson(componentConfigurationJson);
       
        if (componentConfiguration == null) {
            return null;
        }
        String sortColApiName = fieldNamesByColumnNames.get(sortCol);
 
        List<QueryBuilder.FilterClause> filters = new List<QueryBuilder.FilterClause>();
        filters.add(new QueryBuilder.StringFilterClause('Position__c', recordId));
 
        WorkComponentDataController controller;
        if (String.isNotBlank(sortCol) && String.isNotBlank(sortOrder)) {
            QueryBuilder.OrderClause order = new QueryBuilder.OrderClause(sortColApiName, sortOrder);
            controller = new WorkComponentDataController(filters, order);
        }
        else {
            controller = new WorkComponentDataController(filters);
        }
       
        return getApplicationsInner(componentConfiguration, controller);
    }
 
    @TestVisible
    private static List<Application__c> getApplicationsFromJson(String recordsJson) {
        System.debug(recordsJson);
        Dataweave_mapping__mdt mapping = [SELECT Id, DeveloperName FROM Dataweave_mapping__mdt WHERE DeveloperName = 'Application_to_wrapper' LIMIT 1];
        System.debug('mapping ' + mapping);

        String keyMap = TranslateJsonToObjects.fetchMappingFromCustomMetadata(mapping, true);
        System.debug('keyMap ' + keyMap);
        TranslateJsonToObjects translator = new TranslateJsonToObjects(recordsJson, keyMap);
        
        List<Application__c> applications = (List<Application__c>)translator.translateToSObjects('Application__c');
        System.debug('APPLICATIONS');
        DeveloperUtils.printList(applications);
 
        return applications;
    }
 
    @AuraEnabled
    public static void  updateRecords(String recordsJson) {
        List<Application__c> applications = getApplicationsFromJson(recordsJson);
        update applications;
    }
 
    /* Send email to Vendors about status change application and create relation between vendor and position */
    private static void     handleNotifyVendorApplicationStatusChange(List<Application__c> applications) {
        QueryBuilder qb = new QueryBuilder(new Set<String>{ 'Contact__c', 'Vendor__c' }, 'Default_vendor_contact__c');
        QueryBuilder.FilterClause fc = new QueryBuilder.StringFilterClause('Vendor__c', DeveloperUtils.getStringFieldSet(applications, 'Vendor__c'));
 
        qb.addFilterClause(fc);
 
        System.debug('QUERY' + qb.toString());
 
        List<Default_vendor_contact__c> defaultVendorContacts = Database.query(qb.toString());
        Map<Id, Id> contactByVendorId = DeveloperUtils.mapIdToIdField(defaultVendorContacts, 'Vendor__c', 'Contact__c');
 
        Map<Id, Id> contactByRecordId = new Map<Id, Id>();
 
        for (Application__c app: applications) {
            contactByRecordId.put(app.Id, contactByVendorId.get(app.Vendor__c));
        }
 
        List<MailWrapper> mails = new List<MailWrapper>();
        for (Application__c app: applications) {
            String mailType = (app.Status__c != 'Rejected')? 'Application to manager mail' : 'Application rejection email to vendor';
            mails.add(new MailWrapper(app.Id, contactByRecordId.get(app.Id), mailType));
        }
 
        MailHandler.sendEmails(mails);
    }
 
    // private static void     updateApplications(List<Application__c> applications) {
    //     List<Application__c> applicationsToUpdate = new List<Application__c>();

    //     System.debug('Update applications')
    //     for (Application__c app: applications) {
    //         Application__c a = new Application__c();
    //         a.Id = app.Id;
           
    //         if (app.Send_to_hiring_manager__c == 'Yes') {
    //             a.Status__c = 'Sent to hiring manager';
    //         }
    //         else {
    //             a.Status__c = 'Rejected';
    //         }
 
    //         applicationsToUpdate.add(a);
    //     }
 
    //     update applicationsToUpdate;
    // }
 
    private static void     updatePositionStatus(Id positionId) {
        Position__c pos = new Position__c(
            Id = positionId,
            Processing_status__c = 'Candidates offered and in review of manager'
        );
 
        update pos;
    }
 
    private static void shareApplicationsWithHiringManager(Id positionId, List<Application__c> applications, Id hiringManagerUserId) {
        List<Id> applicationIds = new List<Id>();
 
        for (Application__c app: applications) {
            if (app.Send_to_hiring_manager__c == 'Yes') {
                applicationIds.add(app.Id);
            }
        }
 
        ApplicationSharingHandler.shareRecordsWithHiringManager(positionId, applicationIds, hiringManagerUserId);
        CandidateSharingHandler.shareRecordsWithHiringManager(applicationIds, hiringManagerUserId);
        createTasks(applicationIds, hiringManagerUserId);
    }

    public static void createTasks(List<Id> applicationIds, Id hiringManagerUserId){
        List<TaskHandler.TaskWrapper> taskWrapperList = new List<TaskHandler.TaskWrapper>();
        for(Id applicationId : applicationIds){
            TaskHandler.TaskWrapper tw = new TaskHandler.TaskWrapper(
                'new_application_hiring_manager',
                applicationId,
                hiringManagerUserId,
                Date.today()
            );
            taskWrapperList.add(tw);
        }
        TaskHandler.createTasks(taskWrapperList);
    }
 
    private static void handleApprovalRequests(List<Application__c> applications, Id hiringManagerUserId) {
        System.debug('HANDLE APPROVAL REQUEST');
        List<ApprovalController.ApprovalHandlerWrapper> wrappers = new List<ApprovalController.ApprovalHandlerWrapper>();
        Map<Id, List<ProcessInstanceWorkitem>> pendingApprovalRequestsByApplicationId = ApprovalController.getPendingApprovalRequestsByTargetObject(
            new List<Id>(DeveloperUtils.getIdFieldSet(applications, 'Id')), 'Application_to_placement_Aspen');
 
        for (Application__c app: applications) {
            String action = app.Send_to_hiring_manager__c == 'Yes' ? 'Approve' : 'Reject';
            List<ProcessInstanceWorkItem> workItems = pendingApprovalRequestsByApplicationId.get(app.Id);
 
            if (workItems == null || workItems.size() != 1) {
                String error = 'Could not handle approval request for application with id ' + app.Id + ': ';
                error += (workItems == null || workItems.size() == 0)? 'no open request found.' : 'multiple requests found.';
                System.debug(LoggingLevel.ERROR, error);
            }
            else {
                ApprovalController.ApprovalHandlerWrapper wrap = new ApprovalController.ApprovalHandlerWrapper(
                    workItems[0].Id,
                    action,
                    app.Clarification_hiring_desk__c, // This may break
                    hiringManagerUserId
                );
 
                wrappers.add(wrap);
            }
        }

        System.debug('WRAPPERS ' + wrappers);
        ApprovalController.processApprovalRequests(wrappers);
        System.debug('Approval request done');
    }
 
    private static Id getUserId(Id positionId) {
        return [
            SELECT Id
            FROM User
            WHERE ContactId
            IN (
                SELECT Hiring_manager__c
                FROM Position__c
                WHERE Id = :positionId)
            LIMIT 1
        ].Id;
    }
 
    /* Updates ONLY comments written by hiring desk, since no other information is editable in the
    hiring desk review screen. Only updates if comment was written in that screen */
    @AuraEnabled
    public static void  handleRejectApproveApplicationsHiringDesk(String recordsJson, Id positionId) {
        try {
            Id hiringmanagerUserId = getUserId(positionId);

            List<Application__c> applications = getApplicationsFromJson(recordsJson);
            // updateApplications(applications);

            DeveloperUtils.printList(applications);
 
            QueryBuilder.FilterClause fc = new QueryBuilder.StringFilterClause('Id', DeveloperUtils.getStringFieldSet(applications, 'Id'));
            QueryBuilder qb = new QueryBuilder(new Set<String>{'Vendor__c', 'Id', 'Status__c', 'Send_to_hiring_manager__c', 'Clarification_hiring_desk__c'}, 'Application__c');
            qb.addFilterClause(fc);
 
            List<Application__c> applicationsWithVendors = Database.query(qb.toString());
 
            System.debug('Applications with vendors');

            DeveloperUtils.printList(applicationsWithVendors);

            System.debug('notify vendor app status change');
 
            //handleNotifyVendorApplicationStatusChange(applicationsWithVendors);
            System.debug('update position status');
 
            updatePositionStatus(positionId);
 
            System.debug('handle approval req');
 
            handleApprovalRequests(applications, hiringmanagerUserId);
 
            System.debug('Sharing');
            shareApplicationsWithHiringManager(positionId, applications, hiringmanagerUserId);
        }
        catch (Exception e) {
            System.debug(LoggingLevel.Error, e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static Boolean showHiringManagerCockpit(Id positionId){
        if (String.isBlank(positionId)) {
            return false;
        }

        List<String> doNotShowStatuses = new List<String>{'Concept', 'New', 'Rejected', 'Witdrawn'};
        
        Position__c pos = [
            SELECT Status__c, Is_template_position__c, Processing_status__c
            FROM Position__c
            WHERE Id = :positionId
        ];

        return (
            !doNotShowStatuses.contains(pos.Status__c)
            && pos.Processing_status__c != 'New'
            && pos.Is_template_position__c != 'Template_position'
        );
    }
}