force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Account_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Candidate_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Hiring_manager_associated_position__c.field-meta.xml
<CustomField>
    <fullName>Hiring_manager_associated_position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring manager associated position</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Is_preferred_candidate__c.field-meta.xml
<CustomField>
    <fullName>Is_preferred_candidate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is preferred candidate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Position_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Reason_rejection_hiring_desk__c.field-meta.xml
<CustomField>
    <fullName>Reason_rejection_hiring_desk__c</fullName>
    <description>Reason for rejection by hiring desk</description>
    <label>Reason for rejection</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Reason_rejection_hiring_desk</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Send_to_hiring_manager__c.field-meta.xml
<CustomField>
    <fullName>Send_to_hiring_manager__c</fullName>
    <description>Internal field for hiring desk to keep track of applicants they like or dislike</description>
    <inlineHelpText>Indicate whether you intend to send an applicant to the next stage. For internal use only.</inlineHelpText>
    <label>Send to hiring manager</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intake requested</fullName>
            </value>
            <value>
                <fullName>Intake planned</fullName>
            </value>
            <value>
                <fullName>Intake done</fullName>
            </value>
            <value>
                <fullName>Position offered</fullName>
            </value>
            <value>
                <fullName>Position not offered</fullName>
            </value>
            <value>
                <fullName>Placement</fullName>
            </value>
            <value>
                <fullName>Position not accepted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Sent to hiring manager</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Candidate withdrawn</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Placement requested</fullName>
            </value>
            <value>
                <fullName>Information requested for placement</fullName>
            </value>
            <value>
                <fullName>Invited for intake</fullName>
                <isActive>false</isActive>
                <label>Invited for intake</label>
            </value>
            <value>
                <fullName>Rejected by hiring manager</fullName>
                <isActive>false</isActive>
                <label>Rejected by hiring manager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications (Vendor)</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Account_for_candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Candidates (Vendor)</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Function title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Account_for_positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Has_preferred_candidates__c.field-meta.xml
<CustomField>
    <fullName>Has_preferred_candidates__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has preferred candidate(s)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Hiring_manager__c.field-meta.xml
<CustomField>
    <fullName>Hiring_manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Positions (Hiring manager)</relationshipLabel>
    <relationshipName>Hiring_manager_for_positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Positions (Position)</relationshipLabel>
    <relationshipName>Positions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Afgewezen</label>
            </value>
            <value>
                <fullName>Concept</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Applications with hiring manager</fullName>
                <isActive>false</isActive>
                <label>Applications with hiring manager</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Sent to hiring manager</fullName>
                <isActive>false</isActive>
                <label>Sent to hiring manager</label>
            </value>
            <value>
                <fullName>Unapproved</fullName>
                <isActive>false</isActive>
                <label>Unapproved</label>
            </value>
            <value>
                <fullName>Up for correction</fullName>
                <isActive>false</isActive>
                <label>Up for correction</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vendor_position_application__c/Vendor_position_application__c.object-meta.xml
<CustomObject>
    <description>Object used to store information about applications on a position per vendor, such as number of applications a vendor has made on a position.</description>
    <label>Vendor position application</label>
    <nameField>
        <label>Vendor position application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor position applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_position_application__c/fields/Number_of_active_applications__c.field-meta.xml
<CustomField>
    <fullName>Number_of_active_applications__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of active applications</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vendor_position_application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Vendor position applications</relationshipLabel>
    <relationshipName>Vendor_position_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_position_application__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendor position applications</relationshipLabel>
    <relationshipName>Vendor_position_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ApplicationTriggerHandler.cls
public without sharing class ApplicationTriggerHandler {
    private System.TriggerOperation triggerOperation;
	private List<Application__c> newList;
	private List<Application__c> oldList;
	private Map<Id, Application__c> newMap;
	private Map<Id, Application__c> oldMap;

    public ApplicationTriggerHandler(System.TriggerOperation triggerOperation, List<Application__c> newList, List<Application__c> oldList, Map<Id, Application__c> newMap, Map<Id, Application__c> oldMap) {
        this.triggerOperation = triggerOperation;
		this.newList = newList;
		this.newMap = newMap;
		this.oldMap = oldMap;
		this.oldList = oldList;
    }

    public void execute() {
		switch on this.triggerOperation {
			when BEFORE_INSERT {
				emptyRejectionReasonForStatus(newList);
				setAccount(newList);
				setVendor(newList);
				setDefaults(this.newList);
			}
			when AFTER_INSERT {
				shareApplicationWithHiringDesk(newList);
				increaseNumberApplicationsSent(newList);
				submitForApproval(newList);
				updatePosition(newList);
			}
			when BEFORE_UPDATE{
				emptyRejectionReasonForStatus(newList);
			}
			when AFTER_UPDATE {
				// removeApplicationSentIfCandidateWithdrawn(newMap, oldMap);
			}
			when AFTER_DELETE {
			}
		}
	}

	public static void updatePosition(List<Application__c> newList) {
		Set<Id> positionsToUpdate = new Set<Id>();
		for (Application__c app: newList) {
			if (app.Is_preferred_candidate__c == true) {
				positionsToUpdate.add(app.Position__c);
			}
		}

		List<Position__c> positions = new List<Position__c>();
		for (Id posId: positionsToUpdate) {
			Position__c p = new Position__c();
			p.Id = posId;
			p.Has_preferred_candidates__c = true;

			positions.add(p);
		}

		update positions;
	}

	public static void submitForApproval(List<Application__c> newList) {
		for (Application__c app: newList) {
			if (app.Is_preferred_candidate__c == false) {
				ApprovalController.submitApprovalRequest(app.Id);
			}
		}
	}

	public static void setAccount(List<Application__c> newList) {
		Set<Id> positionIds = new Set<Id>();
		for (Application__c app : newList) {
			positionIds.add(app.Position__c);
		}

		Map<Id, Position__c> accByPosition = new Map<Id, Position__c>([SELECT Id, Account__c FROM Position__c WHERE Id IN :positionIds]);

		for (Application__c app : newList) {
			if (String.isBlank(app.Position__c)) {
				app.addError('No position set on application!');
			}
			else {
				app.Account__c = accByPosition.get(app.Position__c).Account__c;
			}
		}
	}

	public static void setVendor(List<Application__c> newList) {
		if (UserInfo.getUserType() != 'Standard') {
			Id vendor = [
				SELECT AccountId FROM Contact WHERE Id IN (
				SELECT ContactId FROM User WHERE Id = :UserInfo.getUserId())
				LIMIT 1].AccountId;

				System.debug('VENDOR: ' + vendor);
				
			for (Application__c app: newList) {
				if (String.isBlank(app.Vendor__c)) {
					app.Vendor__c = vendor;
				}
			}
		}
	}

	// public void setHiringManagerUser(List<Application__c> newList) {
	// 	Set<Id> positionIds = new Set<Id>();
	// 	for (Application__c app : newList) {
	// 		positionIds.add(app.Position__c);
	// 	}

	// 	Map<Id,Position__c> relatedPositions = new Map<Id, Position__c>([SELECT Id, Hiring_Manager__c, Hiring_Manager__r.User__c FROM Position__c WHERE Id IN :positionIds]);
		
	// 	for (Application__c app : newList) {
	// 		app.Hiring_manager_associated_position__c = app.Hiring_manager_associated_position__c == null ? relatedPositions.get(app.Position__c).Hiring_Manager__r.User__c : app.Hiring_manager_associated_position__c;
	// 	}
	// }

	public void shareApplicationWithHiringDesk(List<Application__c> newList) {
		for (Application__c app: newList) {
			ApplicationSharingHandler.shareRecordWithHiringDesk(app.Id);
		}
	}

	public void setDefaults(List<Application__c> newList) {
		Set<Id>	candidateIds = new Set<Id>();
		for (Application__c app: newList) {
			candidateIds.add(app.Candidate__c);
			app.Status__c = 'New';
		}

		Map<Id, Candidate__c> candidates = new Map<Id, Candidate__c>([SELECT Name FROM Candidate__c WHERE Id IN :candidateIds]);
		for (Application__c app: newList) {
			if (String.isBlank(app.Candidate__c)) {
				app.addError('No candidate set!');
			}
			else {
				app.Name = candidates.get(app.Candidate__c).Name;
			}
		}
	}

	public void emptyRejectionReasonForStatus(List<Application__c> newList) {
		for (Application__c app: newList) {
			if (app.Send_to_hiring_manager__c != 'No') {
				app.Reason_rejection_hiring_desk__c = '';
			}
		}
	}

	public void increaseNumberApplicationsSent(List<Application__c> newList) {
		Map<Id, Set<Id>> positionIdsByVendor = new Map<Id, Set<Id>>();

		for (Application__c app: newList) {
			Id vendorId = app.Vendor__c;
			if (positionIdsByVendor.get(vendorId) == null) {
				positionIdsByVendor.put(vendorId, new Set<Id>());
			}
			positionIdsByVendor.get(vendorId).add(app.Position__c);
		}
		
		System.debug('positionIdsByVendor' + positionIdsByVendor);

		Set<Id> posIds = new Set<Id>();

		for (Set<Id> ids: positionIdsByVendor.values()) {
			posIds.addAll(ids);
		}

		List<Vendor_position_application__c> vendor_position_applications = [
			SELECT Vendor__c, Position__c, Number_of_active_applications__c
			FROM Vendor_position_application__c 
			WHERE (
				Vendor__c IN :positionIdsByVendor.keySet()
				AND 
				Position__c IN :posIds
			)
		];

		System.debug('vendor_position_applications' + vendor_position_applications);

		List<Vendor_position_application__c> connsToUpdate = new List<Vendor_position_application__c>();
		for (Vendor_position_application__c conn: vendor_position_applications) {
			Set<Id> tmpPosIds = positionIdsByVendor.get(conn.Vendor__c);
			if (tmpPosIds != null && tmpPosIds.contains(conn.Position__c)) {
				conn.Number_of_active_applications__c++;
				System.debug((conn.Number_of_active_applications__c));
				connsToUpdate.add(conn);
			}
		}

		System.debug(connsToUpdate);
		update connsToUpdate;
	}

	// public void removeApplicationSentIfCandidateWithdrawn(Map<Id, Application__c> newMap, Map<Id, Application__c> oldMap) {
	// 	List<Vendor_position_application__c> recordsToRemoveOneCounter = new List<Vendor_position_application__c>();
	// 	Set<Id> recordIds = new Set<Id>();

	// 	for(Id recordId : newMap.keySet()) {
	// 		if(newMap.get(recordId).Status__c != oldMap.get(recordId).Status__c
	// 		&& newMap.get(recordId).Status__c == 'Candidate withdrawn') {
	// 			recordIds.add(recordId);
	// 		}
	// 	}

	// 	if(!recordIds.isEmpty()) {
	// 		List<Vendor_position_application__c> updatedApplis = new List<Vendor_position_application__c>();

	// 		List<Vendor_position_application__c> vendorPositionApplications = [
	// 			SELECT Number_of_active_applications__c
	// 			FROM Vendor_position_application__c 
	// 			WHERE Id IN :recordIds
	// 		];
			
	// 		for(Vendor_position_application__c appli : vendorPositionApplications) {
	// 			Vendor_position_application__c updatedAppli = new Vendor_position_application__c(
	// 				Id = appli.Id,
	// 				Number_of_active_applications__c = appli.Number_of_active_applications__c - 1
	// 			);

	// 			updatedApplis.add(updatedAppli);
	// 		}

	// 		if(!updatedApplis.isEmpty()) {
	// 			update updatedApplis;
	// 		}
	// 	}
	// }
}