force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Available_from__c.field-meta.xml
<CustomField>
    <fullName>Available_from__c</fullName>
    <label>Available from</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Candidate_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Holds contact information for specific user at the vendor that manages this application.</description>
    <inlineHelpText>Holds contact information for specific user at the vendor that manages this application.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Desired_rate__c.field-meta.xml
<CustomField>
    <fullName>Desired_rate__c</fullName>
    <label>Desired rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Hours_available__c.field-meta.xml
<CustomField>
    <fullName>Hours_available__c</fullName>
    <inlineHelpText>Hours candidate is available to work per week</inlineHelpText>
    <label>Hours available</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Position_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Reason_rejection_hd_editable__c.field-meta.xml
<CustomField>
    <fullName>Reason_rejection_hd_editable__c</fullName>
    <formula>NOT(ISPICKVAL(Send_to_hiring_manager__c, &apos;No&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reason rejection hd editable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Reason_rejection_hiring_desk__c.field-meta.xml
<CustomField>
    <fullName>Reason_rejection_hiring_desk__c</fullName>
    <description>Reason for rejection by hiring desk</description>
    <label>Reason for rejection</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Reason_rejection_hiring_desk</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Review_score__c.field-meta.xml
<CustomField>
    <fullName>Review_score__c</fullName>
    <inlineHelpText>Please review how well the candidate&apos;s skillset and personality match the position they were offered for</inlineHelpText>
    <label>Review score</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rating_list</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Send_to_hiring_manager__c.field-meta.xml
<CustomField>
    <fullName>Send_to_hiring_manager__c</fullName>
    <description>Internal field for hiring desk to keep track of applicants they like or dislike</description>
    <inlineHelpText>Indicate whether you intend to send an applicant to the next stage. For internal use only.</inlineHelpText>
    <label>Send to hiring manager</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intake requested</fullName>
            </value>
            <value>
                <fullName>Intake planned</fullName>
            </value>
            <value>
                <fullName>Intake done</fullName>
            </value>
            <value>
                <fullName>Position offered</fullName>
            </value>
            <value>
                <fullName>Position not offered</fullName>
            </value>
            <value>
                <fullName>Placement</fullName>
            </value>
            <value>
                <fullName>Position not accepted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Sent to hiring manager</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Candidate withdrawn</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Placement requested</fullName>
            </value>
            <value>
                <fullName>Information requested for placement</fullName>
            </value>
            <value>
                <fullName>Invited for intake</fullName>
                <isActive>false</isActive>
                <label>Invited for intake</label>
            </value>
            <value>
                <fullName>Rejected by hiring manager</fullName>
                <isActive>false</isActive>
                <label>Rejected by hiring manager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications (Vendor)</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Candidates (Vendor)</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Function title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Hiring_manager__c.field-meta.xml
<CustomField>
    <fullName>Hiring_manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Positions (Hiring manager)</relationshipLabel>
    <relationshipName>Hiring_manager_for_positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Internal_deadline__c.field-meta.xml
<CustomField>
    <fullName>Internal_deadline__c</fullName>
    <description>Deadline by which to fill position</description>
    <label>Internal deadline</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Positions (Position)</relationshipLabel>
    <relationshipName>Positions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Afgewezen</label>
            </value>
            <value>
                <fullName>Concept</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Applications with hiring manager</fullName>
                <isActive>false</isActive>
                <label>Applications with hiring manager</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Sent to hiring manager</fullName>
                <isActive>false</isActive>
                <label>Sent to hiring manager</label>
            </value>
            <value>
                <fullName>Unapproved</fullName>
                <isActive>false</isActive>
                <label>Unapproved</label>
            </value>
            <value>
                <fullName>Up for correction</fullName>
                <isActive>false</isActive>
                <label>Up for correction</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WorkComponentDataControllerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class WorkComponentDataControllerTest {
    public class ApplicationWrapper {
        @AuraEnabled public Id applicationId;
        @AuraEnabled public String applicationName;
        @AuraEnabled public Date availableFrom;
        @AuraEnabled public Decimal rate;
        @AuraEnabled public Decimal hoursAvailable;
        @AuraEnabled public Decimal rating;
        @AuraEnabled public String status;
        @AuraEnabled public String comment;
        @AuraEnabled public String rejectionReasonHiringDesk;
        @AuraEnabled public String sendToHiringManager;
        @AuraEnabled public Boolean reasonRejectionEditable;

        /* Position fields */
        // TODO: something about money
        @AuraEnabled public Id positionId;
        @AuraEnabled public String positionName;
        @AuraEnabled public Datetime deadline;
        @AuraEnabled public Id hiringManagerId;
        @AuraEnabled public String hiringManagerName;

        /* Candidate fields */
        @AuraEnabled public Id candidateId;
        @AuraEnabled public String candidateName;

        /* Contact fields */
        @AuraEnabled public Id contactId;
        @AuraEnabled public String contactName;
        @AuraEnabled public String contactPhone;
        @AuraEnabled public String contactEmail;

        /* Vendor fields */
        @AuraEnabled public Id vendorId;
        @AuraEnabled public String vendorName;

        /* Other fields */
        @AuraEnabled public Id cvId;
        @AuraEnabled public Id versionId;
    }

    public static Map<String, String> fieldNamesByColumnNames = new Map<String, String> {
        'applicationId' => 'Id',
        'applicationName' => 'Name',
        'availableFrom' => 'Available_from__c',
        'rate' => 'Desired_rate__c',
        'hoursAvailable' => 'Hours_available__c',
        'rating' => 'Review_score__c',
        'status' => 'Status__c',
        'comment' => 'Comment__c',
        'positionId' => 'Position__c',
        'positionName' => 'Position__r.Name',
        'deadline' => 'Position__r.Internal_deadline__c',
        'hiringManagerId' => 'Position__r.Hiring_manager__r.Id',
        'hiringManagerName' => 'Position__r.Hiring_manager__r.Name',
        'candidateId' => 'Candidate__c',
        'candidateName' => 'Candidate__r.Name',
        'contactId' => 'Contact__c',
        'contactName' => 'Contact__r.Name',
        'contactPhone' => 'Contact__r.Phone',
        'contactEmail' => 'Contact__r.Email',
        'vendorId' => 'Vendor__c',
        'vendorName' => 'Vendor__r.Name',
        'rejectionReasonHiringDesk' => 'Reason_rejection_hiring_desk__c',
        'sendToHiringManager' => 'Send_to_hiring_manager__c',
        'reasonRejectionEditable' => 'Reason_rejection_hd_editable__c',
        'cvId' => 'cvId',
        'versionId' => 'versionId'
    };

    public static Map<String, String> columnNamesByFieldNames = DeveloperUtils.reverseMap(fieldNamesByColumnNames);
    @isTest
    static void testGetData() {
        User u = TestDataFactory.getUser();

        insert u;
        System.runAs(u) {
        // List<Application__c> appList = new List<Application__c>();
        //     Position__c p = TestDataFactory.getPosition(false);
        //     insert p;
        //     for (Integer i = 0; i < 8; ++i) {
        //         appList.add(TestDataFactory.getApplicationWithCv('Fn_' + i, 'Ln_' + i, p));
        //         Application__c app = appList[i];
        //     }
        //     String componentName = 'Standard hiring desk workcomponent';

        //     Test.startTest();
        //     WorkcomponentSettingsController.ComponentConfiguration conf = WorkcomponentSettingsController.getSettings(componentName, columnNamesByFieldNames);
            
        //     List<QueryBuilder.FilterClause> filters = new List<QueryBuilder.FilterClause>();
        //     filters.add(new QueryBuilder.StringFilterClause('Position__c', p.Id));
        //     WorkComponentDataController contr = new WorkComponentDataController(filters);

        //     List<Map<String, Object>> res = contr.getData(conf, columnNamesByFieldNames);//(data, columnNamesByFieldNames, conf.queryFields);
        //     Test.stopTest();

        //     System.assert(res.size() == 8);
        }
    }

    @isTest
    static void testGetDataNoApplications() {
        User u = TestDataFactory.getUser();

        insert u;
        // System.runAs(u) {
        //     List<Application__c> appList = new List<Application__c>();
        //     Position__c p = TestDataFactory.getPosition(false);
        //     insert p;
        //     String componentName = 'Standard hiring desk workcomponent';

        //     Test.startTest();
        //     WorkcomponentSettingsController.ComponentConfiguration conf = WorkcomponentSettingsController.getSettings(componentName, columnNamesByFieldNames);
        //     List<QueryBuilder.FilterClause> filters = new List<QueryBuilder.FilterClause>();
        //     filters.add(new QueryBuilder.StringFilterClause('Position__c', p.Id));
        //     WorkComponentDataController contr = new WorkComponentDataController(filters);

        //     List<Map<String, Object>> res = contr.getData(conf, columnNamesByFieldNames);//(data, columnNamesByFieldNames, conf.queryFields);
        //     Test.stopTest();

        //     System.assert(res == null);
        // }
    }
}