force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Account_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Desired_rate__c.field-meta.xml
<CustomField>
    <fullName>Desired_rate__c</fullName>
    <label>Desired rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Position_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Reason_rejection_hiring_desk__c.field-meta.xml
<CustomField>
    <fullName>Reason_rejection_hiring_desk__c</fullName>
    <description>Reason for rejection by hiring desk</description>
    <label>Reason for rejection</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Reason_rejection_hiring_desk</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Send_to_hiring_manager__c.field-meta.xml
<CustomField>
    <fullName>Send_to_hiring_manager__c</fullName>
    <description>Internal field for hiring desk to keep track of applicants they like or dislike</description>
    <inlineHelpText>Indicate whether you intend to send an applicant to the next stage. For internal use only.</inlineHelpText>
    <label>Send to hiring manager</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intake requested</fullName>
            </value>
            <value>
                <fullName>Intake planned</fullName>
            </value>
            <value>
                <fullName>Intake done</fullName>
            </value>
            <value>
                <fullName>Position offered</fullName>
            </value>
            <value>
                <fullName>Position not offered</fullName>
            </value>
            <value>
                <fullName>Placement</fullName>
            </value>
            <value>
                <fullName>Position not accepted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Sent to hiring manager</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Candidate withdrawn</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Placement requested</fullName>
            </value>
            <value>
                <fullName>Information requested for placement</fullName>
            </value>
            <value>
                <fullName>Invited for intake</fullName>
                <isActive>false</isActive>
                <label>Invited for intake</label>
            </value>
            <value>
                <fullName>Rejected by hiring manager</fullName>
                <isActive>false</isActive>
                <label>Rejected by hiring manager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications (Vendor)</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mailtemplate__c/Mailtemplate__c.object-meta.xml
<CustomObject>
    <label>Mailtemplate</label>
    <nameField>
        <label>Mailtemplate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mailtemplates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Function title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Account_for_positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Hiring_manager__c.field-meta.xml
<CustomField>
    <fullName>Hiring_manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Positions (Hiring manager)</relationshipLabel>
    <relationshipName>Hiring_manager_for_positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Positions (Position)</relationshipLabel>
    <relationshipName>Positions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Processing_status__c.field-meta.xml
<CustomField>
    <fullName>Processing_status__c</fullName>
    <label>Processing status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Distributed</fullName>
            </value>
            <value>
                <fullName>Candidates offered and in review of manager</fullName>
            </value>
            <value>
                <fullName>Interviews planned</fullName>
            </value>
            <value>
                <fullName>Placement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Afgewezen</label>
            </value>
            <value>
                <fullName>Concept</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Applications with hiring manager</fullName>
                <isActive>false</isActive>
                <label>Applications with hiring manager</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Sent to hiring manager</fullName>
                <isActive>false</isActive>
                <label>Sent to hiring manager</label>
            </value>
            <value>
                <fullName>Unapproved</fullName>
                <isActive>false</isActive>
                <label>Unapproved</label>
            </value>
            <value>
                <fullName>Up for correction</fullName>
                <isActive>false</isActive>
                <label>Up for correction</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WorkcomponentApplicationsControllerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class WorkcomponentApplicationsControllerTest {
    private static List<WorkComponentApplicationsController.ApplicationWrapper> getWrappersFromApplications(List<Application__c> apps) {
        List<WorkComponentApplicationsController.ApplicationWrapper> aws = new List<WorkComponentApplicationsController.ApplicationWrapper>();
 
        for (Application__c app: apps) {
            WorkComponentApplicationsController.ApplicationWrapper aw = new WorkComponentApplicationsController.ApplicationWrapper();
 
            aw.applicationName = app.Name;
            aw.Id = app.Id;
            aw.status = app.Status__c;
            aw.vendorId = app.Vendor__c;
            aw.vendorName = app.Vendor__r?.Name;
            aw.rate = app.Desired_rate__c;
            aw.sendToHiringManager = app.Send_to_hiring_manager__c;
            aw.rejectionReasonHiringDesk = app.Reason_rejection_hiring_desk__c;
 
            aws.add(aw);
        }
 
        return aws;
    }

    @isTest
    static void testGetData() {
        Account a = TestDataFactory.getAccount();
        a.Hiring_desk_group_id__c = SchemaUtils.getGroupByName('Hero hiring desk');
        
        insert a;

        User u = TestDataFactory.getUserNoAccount();

        insert u;
        System.runAs(u) {
            List<Application__c> appList = new List<Application__c>();
            Position__c p = TestDataFactory.getPosition(false);
            p.Account__c = a.Id;

            insert p;

            Account v = TestDataFactory.getVendor();
            insert v;

            for (Integer i = 0; i < 8; ++i) {
                appList.add(TestDataFactory.getApplicationWithCv('Fn_' + i, 'Ln_' + i, p, v));
                Application__c app = appList[i];
            }

            Set<Id> appIds = new Set<Id>();
            for (Application__c app: appList) {
                appIds.add(app.Id);
            }
            String componentName = 'Standard hiring desk workcomponent';

            WorkcomponentSettingsController.ComponentConfiguration conf = WorkcomponentApplicationsController.getSettings(componentName);
            List<WorkcomponentApplicationsController.ApplicationWrapper> cppWrappers = WorkcomponentApplicationsController.getData(JSON.serialize(conf), 'applicationName', 'asc', p.Id);

            for (WorkcomponentApplicationsController.ApplicationWrapper w: cppWrappers) {
                System.assert(w.cvId != null);
                System.assert(appIds.contains(w.Id));
            }
        }
    }

    @isTest
    static void testGetDataNoApplications() {
        User u = TestDataFactory.getUserNoAccount();

        insert u;
        System.runAs(u) {
            Position__c p = TestDataFactory.getPosition(false);
            insert p;

            String componentName = 'Standard hiring desk workcomponent';

            Test.startTest();
            WorkcomponentSettingsController.ComponentConfiguration conf = WorkcomponentApplicationsController.getSettings(componentName);
            List<WorkcomponentApplicationsController.ApplicationWrapper> cppWrappers = WorkcomponentApplicationsController.getData(JSON.serialize(conf), 'applicationName', 'asc', p.Id);
            Test.stopTest();

            System.assert(cppWrappers.size() == 0);
        }
    }

    @isTest
    static void testGetDataNotRejectedNotAtHiringManager() {
        Account a = TestDataFactory.getAccount();
        a.Hiring_desk_group_id__c = SchemaUtils.getGroupByName('Hero hiring desk');
        
        insert a;

        User u = TestDataFactory.getUserNoAccount();

        insert u;
        
        System.runAs(u) {
            List<Application__c> appList = new List<Application__c>();
            Position__c p = TestDataFactory.getPosition(false);
            p.Account__c = a.Id;
            insert p;

            Account v = TestDataFactory.getVendor();
            insert v;

            for (Integer i = 0; i < 8; ++i) {
                appList.add(TestDataFactory.getApplicationWithCv('Fn_' + i, 'Ln_' + i, p, v));
                Application__c app = appList[i];
                app.Send_to_hiring_manager__c = 'Yes';
            }

            for (Integer i = 0; i < 2; ++i) {
                Application__c app = appList[i];
                app.Status__c = 'Rejected';
            }

            for (Integer i = 4; i < 6; ++i) {
                Application__c app = appList[i];
                app.Status__c = 'Sent to hiring manager';
            }

            Set<String> statuses = new Set<String>{'Rejected', 'Sent to hiring manager'};
            update appList;

            Set<Id> appIds = new Set<Id>();
            for (Application__c app: appList) {
                if (!statuses.contains(app.Status__c))
                    appIds.add(app.Id);
            }
            String componentName = 'Hiring desk review component';

            Test.startTest();
            WorkcomponentSettingsController.ComponentConfiguration conf = WorkcomponentApplicationsController.getSettings(componentName);
            List<WorkcomponentApplicationsController.ApplicationWrapper> cppWrappers = WorkcomponentApplicationsController.getApplicationsProcessable(JSON.serialize(conf), 'applicationName', 'asc', p.Id);
            Test.stopTest();

            System.debug('WRAPPERS ' + cppWrappers.size());
            System.assert(cppWrappers.size() == 4);
            for (WorkcomponentApplicationsController.ApplicationWrapper w: cppWrappers) {
                if (statuses.contains(w.status)) {
                    System.assert(!appIds.contains(w.Id));
                }
                else {
                    System.assert(appIds.contains(w.Id));
                }
            }
        }
    }

    // Has to be see all data in order to access custom metadata
    @isTest(SeeAllData=true)
    static void getApplicationFromJsonTest() {
        String appString  = '[{"Id":"a0R5t000002drThEAI","rejectionReasonHiringDesk":"Other"}]';

        List<Application__c> apps = WorkcomponentApplicationsController.getApplicationsFromJson(appString);

        System.assertEquals(apps[0].Reason_rejection_hiring_desk__c, 'Other');
        System.assertEquals(apps[0].Id, 'a0R5t000002drThEAI');
    }

    @isTest
    static void handleRejectApproveTest() {
        Account acc = TestDataFactory.getAccount();
        acc.Hiring_desk_group_id__c = SchemaUtils.getGroupByName('Hero hiring desk');
        
        insert acc;

        Contact c = TestDataFactory.getContact('Bob', 'Vendor', acc);

        insert c;

        User u = TestDataFactory.getPortalUser(acc, c);

        insert u;

        System.runAs(u) {
            Mailtemplate__c mt1 = TestDataFactory.getConnectedMailTemplate('Application accepted: {{Name}}', 'Next stage baby', 'Application to manager mail', acc);
            Mailtemplate__c mt2 = TestDataFactory.getConnectedMailTemplate('Application rejected: {{Name}}', 'No thank you', 'Application rejection email to vendor', acc);

            List<String> rejectedApproved = new List<String>{'Sent to hiring manager', 'Rejected'};
            List<Application__c> appList = new List<Application__c>();
            Position__c p = TestDataFactory.getPosition(false);
            p.Status__c = 'Open';
            p.Account__c = acc.Id;
            p.Hiring_manager__c = c.Id;
            insert p;

            Account vend = TestDataFactory.getVendor();

            insert vend;
            Boolean prev = true;
            for (Integer i = 0; i < 8; ++i) {
                appList.add(TestDataFactory.getApplication('Fn_' + i, 'Ln_' + i, p, vend));
                Application__c app = appList[i];
                app.Send_to_hiring_manager__c = prev? 'Yes' : 'No';
                prev = !prev;
            }

            insert appList;

            Set<Id> appIds = new Set<Id>();
            for (Application__c app: appList) {
                appIds.add(app.Id);
            }

            System.debug('START TEST');
            Test.startTest();
            List<WorkcomponentApplicationsController.ApplicationWrapper> wraps = 
            getWrappersFromApplications(appList);
            WorkcomponentApplicationsController.handleRejectApproveApplicationsHiringDesk(JSON.serialize(wraps), 
            p.Id);
            Test.stopTest();

            List<Application__c> apps = [SELECT Status__c FROM Application__c];
            Position__c pos = [SELECT Id, Processing_status__c FROM Position__c WHERE Id = :p.Id LIMIT 1];

            System.assert(pos.Processing_status__c == 'Candidates offered and in review of manager');

            for (Application__c app: apps) {
                System.assert(rejectedApproved.contains(app.Status__c));
            }
        }
    }
}