force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Position_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications (Vendor)</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Function title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Max_number_of_applicants_number__c.field-meta.xml
<CustomField>
    <fullName>Max_number_of_applicants_number__c</fullName>
    <formula>VALUE(TEXT(Max_number_of_applicants_per_supplier__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Max number of applicants number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Positions (Position)</relationshipLabel>
    <relationshipName>Positions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_position_application__c/Vendor_position_application__c.object-meta.xml
<CustomObject>
    <description>Object used to store information about applications on a position per vendor, such as number of applications a vendor has made on a position.</description>
    <label>Vendor position application</label>
    <nameField>
        <label>Vendor position application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor position applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_position_application__c/fields/Number_of_active_applications__c.field-meta.xml
<CustomField>
    <fullName>Number_of_active_applications__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of active applications</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vendor_position_application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Vendor position applications</relationshipLabel>
    <relationshipName>Vendor_position_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_position_application__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendor position applications</relationshipLabel>
    <relationshipName>Vendor_position_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ApplicationFormController.cls
public without sharing class ApplicationFormController {
    class NumApplication {
        @AuraEnabled
        public Decimal numApplications;
        @AuraEnabled
        public Decimal numAllowed;
    }
    
    @AuraEnabled(cacheable=true)
    public static Id getApplicationRecordTypeId(Id positionId){
        Id positionRecordTypeId = [SELECT RecordTypeId FROM Position__c WHERE Id = :positionId LIMIT 1].RecordTypeId;

        String recordTypeName = SchemaUtils.getRecordTypeName('Position__c', positionRecordTypeId);
        Id applicationRecordTypeId = SchemaUtils.getRecordTypeId('Application__c', recordTypeName);

        return applicationRecordTypeId;
    }

    @AuraEnabled(cacheable=true)
    public static NumApplication getNumApplications(Id recordId) {
        Id vendor = [
            SELECT AccountId FROM Contact WHERE Id IN (
            SELECT ContactId FROM User WHERE Id = :UserInfo.getUserId())
            LIMIT 1].AccountId;

            System.debug('PositionID ' + recordId);
            System.debug('Vendor' + vendor);

        List<Vendor_position_application__c> conns = [
            SELECT Number_of_active_applications__c 
            FROM Vendor_position_application__c 
            WHERE Position__c = :recordId
            AND Vendor__c = :vendor
            LIMIT 1
        ];
        
        System.debug('Conn ' + conns);
        Position__c pos = [
            SELECT Max_number_of_applicants_number__c
            FROM Position__c
            WHERE Id = :recordId
            LIMIT 1
        ];

        System.debug(pos);

        if (conns == null || conns.size() == 0) {
            return null;
        }
        
        NumApplication nApps = new NumApplication();
        nApps.numApplications = conns[0].Number_of_active_applications__c;
        nApps.numAllowed = pos.Max_number_of_applicants_number__c;

        System.debug(nApps);
        return nApps;
    }

    @AuraEnabled
    public static void submitForApproval(Id recordId) {
        ApprovalController.submitApprovalRequest(recordId);
    }
}