force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Account_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Candidate_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Position_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Account_for_candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Function title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Account_for_positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Hiring_manager__c.field-meta.xml
<CustomField>
    <fullName>Hiring_manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Positions (Hiring manager)</relationshipLabel>
    <relationshipName>Hiring_manager_for_positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Positions (Position)</relationshipLabel>
    <relationshipName>Positions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CandidateSharingHandler.cls
public with sharing class CandidateSharingHandler {
    public class CandidateSharingException extends Exception {}

    // private static void shareRecord(List<Id> recordIds, List<Id> recipientIds, String accessLevel, String sharingRule) { // accessLevel is Edit/Read/All
    //     List<Candidate__Share> canShares = new List<Candidate__Share>();
        
    //     for (Id recordId: recordIds) {
    //         for (Id recipientId: recipientIds) {
    //             Candidate__Share canShare = new Candidate__Share();

    //             canShare.ParentId = recordId;
    //             canShare.UserOrGroupId = recipientId;
    //             canShare.AccessLevel = accessLevel;
    //             canShare.RowCause = sharingRule;

    //             canShares.add(canShare);
    //         }
    //     }
        
    //     Database.SaveResult[] sr = Database.insert(canShares, false);
    //     DatabaseResultHandler.handlerDatabaseResults(sr);
    // }

    // private static void shareRecord(List<Id> recordIds, Id recipientId, String accessLevel, String sharingRule) { // accessLevel is Edit/Read/All
    //     shareRecord(recordIds, new List<Id>{recipientId}, accessLevel, sharingRule);
    // }

    // private static void shareRecord(Id recordId, Id recipientId, String accessLevel, String sharingRule) { // accessLevel is Edit/Read/All
    //     shareRecord(new List<Id>{recordId}, new List<Id>{recipientId}, accessLevel, sharingRule);
    // }

    public static void shareRecordWithHiringDesk(Id applicationId) {
        List<Application__c> apps = [SELECT Position__r.Account__r.Hiring_desk_group_id__c, Candidate__c FROM Application__c WHERE Id = :applicationId];

        if (apps == null || apps.size() == 0 || String.isBlank(apps[0].Position__r?.Account__r?.Hiring_desk_group_id__c)) {
            throw new CandidateSharingException('Could not find hiring desk group from account associated with application with Id ' + applicationId);
        }
        
        Id hiringDeskGroupId = apps[0].Position__r.Account__r.Hiring_desk_group_id__c;

        SharingHandler.shareRecord(apps[0].Candidate__c, hiringDeskGroupId, SharingHandler.AccessLevel.READ, Schema.Candidate__Share.RowCause.Hiring_desk__c, 'Candidate__Share');
    }

    public static void shareRecordsWithHiringManager(List<Id> applicationIds, Id hiringManagerUserId) {
        List<Application__c> apps = [SELECT Candidate__c FROM Application__c WHERE Id IN :applicationIds];

        List<Id> candidateIds = new List<Id>(DeveloperUtils.getIdFieldSet(apps, 'Candidate__c'));

        SharingHandler.shareRecord(candidateIds, hiringManagerUserId, SharingHandler.AccessLevel.READ, Schema.Candidate__Share.RowCause.Hiring_manager__c, 'Candidate__Share');
    }
}