force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Account_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Position_for_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Function title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Account_for_positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Hiring_manager__c.field-meta.xml
<CustomField>
    <fullName>Hiring_manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Positions (Hiring manager)</relationshipLabel>
    <relationshipName>Hiring_manager_for_positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Positions (Position)</relationshipLabel>
    <relationshipName>Positions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ApplicationSharingHandler.cls
public without sharing class ApplicationSharingHandler {
    // Without sharing because Customer Community Plus users do not have access to Share objects
    public class ApplicationSharingException extends Exception {}

    // private static void shareRecord(List<Id> recordIds, List<Id> recipientIds, String accessLevel, String sharingRule) { // accessLevel is Edit/Read/All
    //     List<Application__Share> posShares = new List<Application__Share>();
        
    //     for (Id recordId: recordIds) {
    //         for (Id recipientId: recipientIds) {
    //             Application__Share posShare = new Application__Share();

    //             posShare.ParentId = recordId;
    //             posShare.UserOrGroupId = recipientId;
    //             posShare.AccessLevel = accessLevel;
    //             posShare.RowCause = sharingRule;

    //             posShares.add(posShare);
    //         }
    //     }
        
    //     Database.SaveResult[] sr = Database.insert(posShares, false);
    //     DatabaseResultHandler.handlerDatabaseResults(sr);
    // }

    // private static void shareRecord(Id recordId, List<Id> recipientIds, String accessLevel, String sharingRule) { // accessLevel is Edit/Read/All
    //     shareRecord(new List<Id>{recordId}, recipientIds, accessLevel, sharingRule);
    // }

    // private static void shareRecord(List<Id> recordIds, Id recipientId, String accessLevel, String sharingRule) { // accessLevel is Edit/Read/All
    //     shareRecord(recordIds, new List<Id>{recipientId}, accessLevel, sharingRule);
    // }

    // private static void shareRecord(Id recordId, Id recipientId, String accessLevel, String sharingRule) { // accessLevel is Edit/Read/All
    //     shareRecord(new List<Id>{recordId}, new List<Id>{recipientId}, accessLevel, sharingRule);
    // }

    public static void shareRecordWithHiringDesk(Id applicationId) {
        List<Application__c> apps = [SELECT Position__r.Account__r.Hiring_desk_group_id__c FROM Application__c WHERE Id = :applicationId];

        System.debug('Applications: ' + apps);
        System.debug('Applications: ' + apps[0].Position__c);
        System.debug('Applications: ' + apps[0].Position__r?.Account__c);
        System.debug('Applications: ' + apps[0].Position__r?.Account__r?.Hiring_desk_group_id__c);
        if (apps == null || apps.size() == 0 || String.isBlank(apps[0].Position__r?.Account__r?.Hiring_desk_group_id__c)) {
            throw new ApplicationSharingException('Could not find hiring desk group from account associated with application with Id ' + applicationId);
        }
        
        Id hiringDeskGroupId = apps[0].Position__r.Account__r.Hiring_desk_group_id__c;

        SharingHandler.shareRecord(applicationId, hiringDeskGroupId, SharingHandler.AccessLevel.EDIT, Schema.Application__Share.RowCause.Hiring_desk__c, 'Application__Share');
    }

    public static void shareRecordsWithHiringManager(Id positionId, List<Id> applicationIds, Id hiringManagerUserId) {
        SharingHandler.shareRecord(applicationIds, hiringManagerUserId, SharingHandler.AccessLevel.EDIT, Schema.Application__Share.RowCause.Hiring_manager__c, 'Application__Share');
    }
}