force-app/main/default/objects/Default_hiring_desk_contact__c/Default_hiring_desk_contact__c.object-meta.xml
<CustomObject>
    <label>Default hiring desk contact</label>
    <nameField>
        <label>Default hiring desk contact</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Default hiring desk contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Default_hiring_desk_contact__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Default hiring desk contacts</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Default_hiring_desk_contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Default hiring desk contacts</relationshipLabel>
    <relationshipName>Default_hiring_desk_contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement__c/Placement__c.object-meta.xml
<CustomObject>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Placement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Placements</relationshipLabel>
    <relationshipName>Account_for_placements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Placements</relationshipLabel>
    <relationshipName>Position_for_placements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Processing_status__c.field-meta.xml
<CustomField>
    <fullName>Processing_status__c</fullName>
    <label>Processing status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In review by hiring desk</fullName>
            </value>
            <value>
                <fullName>Sent for contracting</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Purchase_contract_status__c.field-meta.xml
<CustomField>
    <fullName>Purchase_contract_status__c</fullName>
    <label>Purchase contract status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contract_status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Sales_contract_status__c.field-meta.xml
<CustomField>
    <fullName>Sales_contract_status__c</fullName>
    <label>Sales contract status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contract_status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Placement_rate_percentage__c/Placement_rate_percentage__c.object-meta.xml
<CustomObject>
    <label>Placement rate percentage</label>
    <nameField>
        <label>Placement rate percentage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement rate percentages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Placement_rate_percentage__c/fields/Placement__c.field-meta.xml
<CustomField>
    <fullName>Placement__c</fullName>
    <label>Placement</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Placement rate percentages</relationshipLabel>
    <relationshipName>Placement_rate_percentages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Placement_rate_percentage__c/fields/Rate_percentage__c.field-meta.xml
<CustomField>
    <fullName>Rate_percentage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate percentage</label>
    <referenceTo>Rate_percentage__c</referenceTo>
    <relationshipLabel>Placement rate percentages</relationshipLabel>
    <relationshipName>Placement_rate_percentages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Function title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Account_for_positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Closed_reason__c.field-meta.xml
<CustomField>
    <fullName>Closed_reason__c</fullName>
    <description>Holds reason why a position did not lead to a placement</description>
    <inlineHelpText>Reason why a position did not lead to a placement</inlineHelpText>
    <label>Closed reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>No candidates found</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Number_of_hires__c.field-meta.xml
<CustomField>
    <fullName>Number_of_hires__c</fullName>
    <label>Number of hires</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Positions (Position)</relationshipLabel>
    <relationshipName>Positions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Processing_status__c.field-meta.xml
<CustomField>
    <fullName>Processing_status__c</fullName>
    <label>Processing status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Distributed</fullName>
            </value>
            <value>
                <fullName>Candidates offered and in review of manager</fullName>
            </value>
            <value>
                <fullName>Interviews planned</fullName>
            </value>
            <value>
                <fullName>Placement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Afgewezen</label>
            </value>
            <value>
                <fullName>Concept</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Applications with hiring manager</fullName>
                <isActive>false</isActive>
                <label>Applications with hiring manager</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Sent to hiring manager</fullName>
                <isActive>false</isActive>
                <label>Sent to hiring manager</label>
            </value>
            <value>
                <fullName>Unapproved</fullName>
                <isActive>false</isActive>
                <label>Unapproved</label>
            </value>
            <value>
                <fullName>Up for correction</fullName>
                <isActive>false</isActive>
                <label>Up for correction</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rate_percentage__c/Rate_percentage__c.object-meta.xml
<CustomObject>
    <label>Rate percentage</label>
    <nameField>
        <label>Rate percentage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate percentages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate_percentage__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rate percentages</relationshipLabel>
    <relationshipName>Rate_percentages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rate_percentage__c/fields/Is_standard__c.field-meta.xml
<CustomField>
    <fullName>Is_standard__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is standard</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PlacementTriggerHandler.cls
public with sharing class PlacementTriggerHandler {
    private System.TriggerOperation triggerOperation;
	private List<Placement__c> newList;
	private List<Placement__c> oldList;
	private Map<Id, Placement__c> newMap;
	private Map<Id, Placement__c> oldMap;

    public PlacementTriggerHandler(System.TriggerOperation triggerOperation, List<Placement__c> newList, List<Placement__c> oldList, Map<Id, Placement__c> newMap, Map<Id, Placement__c> oldMap) {
        this.triggerOperation = triggerOperation;
		this.newList = newList;
		this.newMap = newMap;
		this.oldMap = oldMap;
		this.oldList = oldList;
    }

    public void execute() {
		switch on this.triggerOperation {
			when BEFORE_INSERT {
			}
			when AFTER_INSERT {
				checkSetStatusOnPosition(newList);
				relateStandardRatePercentages(newList);
			}
			when BEFORE_UPDATE{
				checkStatusActive(newMap, oldMap);
			}
			when AFTER_UPDATE {

			}
			when AFTER_DELETE {
			}
		}
    }

	public static void checkStatusActive(Map<Id, Placement__c> newMap, Map<Id, Placement__c> oldMap){
		for(Id placementId : newMap.keySet()){
			if(oldMap.get(placementId).Processing_Status__c != 'Active' 
			&& newMap.get(placementId).Sales_contract_status__c == 'Signed' 
			&& newMap.get(placementId).Purchase_contract_status__c == 'Signed'){
				newMap.get(placementId).Processing_Status__c = 'Active';
			}
		}
	}

	public static void relateStandardRatePercentages(List<Placement__c> placements){
		Set<Id> accountIds = new Set<Id>();

		for(Placement__c pl : placements){
			accountIds.add(pl.Account__c);
		}

		List<Rate_Percentage__c> standardRatePercentagesForAccount = [SELECT Id, Name, Account__c FROM Rate_percentage__c WHERE Account__c IN :accountIds AND Is_standard__c = true];
		Map<String, List<Rate_percentage__c>> ratePercentagesByAccount = new Map<String, List<Rate_percentage__c>>();

		for(Rate_Percentage__c rp : standardRatePercentagesForAccount){
			if(ratePercentagesByAccount.containsKey(rp.Account__c)){
				ratePercentagesByAccount.get(rp.Account__c).add(rp);
			}else{
				ratePercentagesByAccount.put(rp.Account__c, new List<Rate_percentage__c>{rp});
			}
		}
		System.debug(ratePercentagesByAccount);
        List<Placement_rate_percentage__c> prpToInsert = new List<Placement_rate_percentage__c>();
		for(Placement__c pl : placements){
			System.debug(pl.Id);
			System.debug(pl.Account__c);
			if(ratePercentagesByAccount.containsKey(pl.Account__c)){
				for(Rate_percentage__c rp : ratePercentagesByAccount.get(pl.Account__c)){
					System.debug(rp);
					Placement_rate_percentage__c newPRP = new Placement_rate_percentage__c();
					newPRP.Name = rp.Name;
					newPRP.Placement__c = pl.Id;
					newPRP.Rate_percentage__c = rp.Id;
					prpToInsert.add(newPRP);
					System.debug(prpToInsert);				}
			}
		}
		if(prpToInsert.size() > 0){
            insert prpToInsert;
        }
	}

	public static void checkSetStatusOnPosition(List<Placement__c> placements){
		Set<Id> posIds = new Set<Id>();
		for(Placement__c plac : placements){
			posIds.add(plac.Position__c);
		}

		Map<Id, Position__c> positionsById = new Map<Id, Position__c>([SELECT Id, Number_of_hires__c FROM Position__c WHERE Id IN :posIds]);

		List<Position__c> positionsToUpdate = new List<Position__c>();
		Map<Id, Integer> numberOfHiredByPositionId = new Map<Id, Integer>();

		for(Id id : positionsById.keySet()){
			Position__c pos = positionsById.get(id);
			if(Integer.valueOf(pos.Number_of_hires__c) == 1){
				pos.Processing_status__c = 'Placement';
				pos.Status__c = 'Hired';
				pos.Closed_reason__c = 'Hired';
				positionsToUpdate.add(pos);
			}else{
				numberOfHiredByPositionId.put(id, Integer.valueOf(pos.Number_of_hires__c));
			}
		}

		if(numberOfHiredByPositionId.size() > 0){
			AggregateResult[] countedPlacements = [SELECT Position__c, COUNT(Id) FROM Placement__c WHERE Position__c IN :numberOfHiredByPositionId.keySet() GROUP BY Position__c];
			for(AggregateResult ar : countedPlacements){
				if(numberOfHiredByPositionId.get(String.valueOf(ar.get('Position__c'))) == Integer.valueOf(ar.get('expr0'))){
					Position__c posToUpdate = new Position__c();
					posToUpdate.Id = String.valueOf(ar.get('Position__c'));
					posToUpdate.Processing_status__c = 'Placement';
					posToUpdate.Status__c = 'Hired';
					posToUpdate.Closed_reason__c = 'Hired';
					positionsToUpdate.add(posToUpdate);
				}
			}
		}

		update positionsToUpdate;
	}

	public static Map<Id, Id> getContactIds(Set<Id> recordIds){
		//TODO select account, the default hiring desk account, get the contact__c from that default hiring desk account, and put that in a map
		Map<Id, Placement__c> placementPerAccountId = new Map<Id, Placement__c>();
		Map<Id, Id> contactIdPerPlacementId = new Map<Id, Id>();
		
		// Get related account id's
		// Loop through them and fill the emails Set and placementPerAccountId Map
		Map<Id, Placement__c> placements = new Map<Id, Placement__c>([SELECT Id, Account__c, Account__r.Hiring_Desk_Email__c FROM Placement__c WHERE Id IN :recordIds]);
		for(Placement__c p : placements.values()){
			placementPerAccountId.put(p.Account__c, placements.get(p.Id));
		}

		List<Default_hiring_desk_contact__c> defaultContacts = [SELECT Account__c, Contact__c FROM Default_hiring_desk_contact__c WHERE Account__c IN :placementPerAccountId.keySet()];
		for(Default_hiring_desk_contact__c dc : defaultContacts){
			contactIdPerPlacementId.put(placementPerAccountId.get(dc.Account__c).Id, dc.Contact__c);
		}

		return contactIdPerPlacementId;
	}

	public class PlacementTriggerHandlerException extends Exception {}
}