force-app/main/default/objects/Default_hiring_desk_contact__c/Default_hiring_desk_contact__c.object-meta.xml
<CustomObject>
    <label>Default hiring desk contact</label>
    <nameField>
        <label>Default hiring desk contact</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Default hiring desk contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Default_hiring_desk_contact__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Default hiring desk contacts</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Default_hiring_desk_contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Default hiring desk contacts</relationshipLabel>
    <relationshipName>Default_hiring_desk_contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Default_vendor_contact__c/Default_vendor_contact__c.object-meta.xml
<CustomObject>
    <description>Connector between a Vendor and corresponding unique contact that&apos;s the &quot;default&quot; contact</description>
    <label>Default vendor contact</label>
    <nameField>
        <label>Default contact for vendor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Default vendor contact</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Default_vendor_contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Default vendor contact</relationshipLabel>
    <relationshipName>Default_vendor_contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Default_vendor_contact__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Default vendor contact</relationshipLabel>
    <relationshipName>Default_vendor_contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountTriggerTest.cls
@isTest
private class AccountTriggerTest {
	@isTest
	static void createDefaultHiringDeskContactTest() {
		Account a = TestDataFactory.getAccount();
		a.RecordTypeId = SchemaUtils.getRecordTypeId('Account', 'Customer');
		a.Hiring_Desk_Email__c = 'test@hero.eu';

		Test.startTest();
		insert a;
		Test.stopTest();

		Default_hiring_desk_contact__c dc = [SELECT Id FROM Default_hiring_desk_contact__c WHERE Account__c = :a.Id];

		System.assert(dc != null);
	}

	@isTest
	static void createDefaultVendorContactTest() {
		Account a = TestDataFactory.getAccount();
		a.RecordTypeId = SchemaUtils.getRecordTypeId('Account', 'Vendor');
		a.Email__c = 'test@hero.eu';

		Test.startTest();
		insert a;
		Test.stopTest();

		Default_vendor_contact__c dc = [SELECT Id FROM Default_vendor_contact__c WHERE Vendor__c = :a.Id];

		System.assert(dc != null);
	}

	@isTest
	static void updateDefaultHiringDeskContactTest() {
		Account a = TestDataFactory.getAccount();
		a.RecordTypeId = SchemaUtils.getRecordTypeId('Account', 'Customer');
		a.Hiring_Desk_Email__c = 'test1@hero.eu';

		insert a;

		a.Hiring_Desk_Email__c = 'test@hero.eu';
		
		Test.startTest();
		update a;
		Test.stopTest();

		Default_hiring_desk_contact__c dc = [SELECT Id, Contact__c FROM Default_hiring_desk_contact__c WHERE Account__c = :a.Id];
		Contact c = [SELECT Email FROM Contact WHERE Id=:dc.Contact__c LIMIT 1];
		System.assert(c.Email == 'test@hero.eu');
	}

	@isTest
	static void updateDefaultVendorContactTest() {
		Account a = TestDataFactory.getAccount();
		a.RecordTypeId = SchemaUtils.getRecordTypeId('Account', 'Vendor');
		a.Email__c = 'test1@hero.eu';

		insert a;

		a.Email__c = 'test@hero.eu';
		
		Test.startTest();
		update a;
		Test.stopTest();

		Default_vendor_contact__c dc = [SELECT Id, Contact__c FROM Default_vendor_contact__c WHERE Vendor__c = :a.Id];
		Contact c = [SELECT Email FROM Contact WHERE Id=:dc.Contact__c LIMIT 1];
		System.assert(c.Email == 'test@hero.eu');
	}
}