force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Account_for_candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/UniqueId__c.field-meta.xml
<CustomField>
    <fullName>UniqueId__c</fullName>
    <externalId>true</externalId>
    <label>UniqueId</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Candidates (Vendor)</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CandidateTriggerHandlerTest.cls
@istest
public class CandidateTriggerHandlerTest {
	@istest
	static void testNameFormat() {
		Candidate__c c = TestDataFactory.getCandidate('Test', 'von der', 'Tester-Test Bob');
		System.assert(TestUtils.nameAdded(c, 'Candidate__c', 'Test von der Tester-Test Bob'));
	}

	@istest
	static void testUniqueId() {
		Candidate__c c = TestDataFactory.getCandidate('Test', 'von der', 'Tester-Test Bob');

		Test.startTest();
		insert c;
		Test.stopTest();

		// Candidate__c cand = new List<Candidate__c>([SELECT Account__c, Vendor__c, Name, UniqueId__c FROM Candidate__c WHERE Id = :c.Id])[0];
		// String expectedId = cand.Account__c + '_' + cand.Vendor__c + '_' + cand.Name.replace(' ', '_');
		// System.assert(expectedId == cand.UniqueId__c);
	}
}