force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Function title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Positions (Position)</relationshipLabel>
    <relationshipName>Positions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TriggerUtilsTest.cls
@istest
public class TriggerUtilsTest {
    @istest
    static void  testNameFormat() {
        Candidate__c c = TestDataFactory.getCandidate('Test', 'von der', 'Tester-Test Bob');
        TriggerUtils.setFullNames(new List<SObject>{c});
        System.assert(c.Name == 'Test von der Tester-Test Bob');
    }

    @istest
    static void  testAccountAdded() {
        Position__c p = TestDataFactory.getPosition(false);
        System.assert(TestUtils.accountWasAdded(p, 'Position__c'));
    }
}