force-app/main/default/objects/File_object_task__c/File_object_task__c.object-meta.xml
<CustomObject>
    <label>File object task</label>
    <nameField>
        <label>File object task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>File object tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/File_object_task__c/fields/Business_Central_id__c.field-meta.xml
<CustomField>
    <fullName>Business_Central_id__c</fullName>
    <externalId>true</externalId>
    <label>Business Central id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/File_object_task__c/fields/Deadline_date__c.field-meta.xml
<CustomField>
    <fullName>Deadline_date__c</fullName>
    <label>Deadline date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/File_object_task__c/fields/File_object_task__c.field-meta.xml
<CustomField>
    <fullName>File_object_task__c</fullName>
    <label>File object task</label>
    <length>123</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/File_object_task__c/fields/Status_task__c.field-meta.xml
<CustomField>
    <fullName>Status_task__c</fullName>
    <label>Status task</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DossierTaskController.cls
public with sharing class DossierTaskController {
    class DossierTaskControllerException extends Exception {}

    @AuraEnabled(cacheable=true)
    public static List<DossierTaskWrapper> getDossierTasks() {
        List<File_object_task__c> fots = [SELECT Name, Deadline_date__c, Business_Central_id__c, Status_task__c FROM File_object_task__c];

        List<DossierTaskWrapper> dtwToReturn = new List<DossierTaskWrapper>();
        for(File_object_task__c fot : fots){
            DossierTaskWrapper wrapper = new DossierTaskWrapper();
            wrapper.Name = fot.Name;
            wrapper.Deadline_date = fot.Deadline_date__c;
            wrapper.Business_Central_id = fot.Business_Central_id__c;
            wrapper.Status_task = fot.Status_task__c;
            wrapper.Disabled = wrapper.Status_task == 'Open' ? false : true;
            dtwToReturn.add(wrapper);
        }
        return dtwToReturn;
    }

    public class DossierTaskWrapper{
		@AuraEnabled public String Name;
		@AuraEnabled public Date Deadline_date;
		@AuraEnabled public String Business_Central_id;
		@AuraEnabled public String Status_task;
        @AuraEnabled public Boolean Disabled;
	}
}