force-app/main/default/objects/File_object_task__c/File_object_task__c.object-meta.xml
<CustomObject>
    <label>File object task</label>
    <nameField>
        <label>File object task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>File object tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/File_object_task__c/fields/Business_Central_id__c.field-meta.xml
<CustomField>
    <fullName>Business_Central_id__c</fullName>
    <externalId>true</externalId>
    <label>Business Central id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/File_object_task__c/fields/File_object_task__c.field-meta.xml
<CustomField>
    <fullName>File_object_task__c</fullName>
    <label>File object task</label>
    <length>123</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/File_object_task__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <externalId>true</externalId>
    <label>Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/File_object_task__c/fields/Related_to_placement__c.field-meta.xml
<CustomField>
    <fullName>Related_to_placement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related to placement</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>File object tasks</relationshipLabel>
    <relationshipName>File_object_tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/File_object_task__c/fields/Status_task__c.field-meta.xml
<CustomField>
    <fullName>Status_task__c</fullName>
    <label>Status task</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Placement__c/Placement__c.object-meta.xml
<CustomObject>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/DossierTaskControllerTest.cls
@istest
public class DossierTaskControllerTest {
    
    @istest
    public static void testGetDossierTasks(){
        Placement__c placement = TestDataFactory.getPlacement();
        insert placement;

        //TODO Do this in the TestDataFactory, but Vasco told me it was scary
        File_object_task__c fot = new File_object_task__c();
        fot.Name = 'test';
        fot.Status_task__c = 'Open';
        fot.Number__c = '1';
        fot.Related_to_placement__c = placement.Id;
        fot.Business_Central_id__c = 'testBCid';
        insert fot; 

        Test.startTest();
        List<DossierTaskController.DossierTaskWrapper> wrapper = DossierTaskController.getDossierTasks();
        Test.stopTest();

        Assert.areEqual(1, wrapper.size());
        Assert.areEqual(false, wrapper[0].Disabled);

    }
}