force-app/main/default/objects/Timesheet__c/Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <label>Timesheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet__c/fields/Professional__c.field-meta.xml
<CustomField>
    <fullName>Professional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Professional</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timesheet_entry__c/Timesheet_entry__c.object-meta.xml
<CustomObject>
    <label>Timesheet entry</label>
    <nameField>
        <label>Timesheet entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timesheet entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet_entry__c/fields/Timesheet__c.field-meta.xml
<CustomField>
    <fullName>Timesheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Timesheet</label>
    <referenceTo>Timesheet__c</referenceTo>
    <relationshipLabel>Timesheet entries</relationshipLabel>
    <relationshipName>Timesheet_entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TimesheetExportControllerTest.cls
@isTest
public class TimesheetExportControllerTest {
	@isTest
	public static void testTimesheetExportController() {

		Account acc = TestDataFactory.getAccount();
		insert acc;
	
		Contact c = TestDataFactory.getContact();
		c.AccountId = acc.Id;
		insert c;
		
		User u = TestDataFactory.getPortalUser(acc, c);
		insert u;

		Timesheet__c timesheet = TestDataFactory.getTimesheetComplete(c.Id);
		insert timesheet;

		List<Timesheet_entry__c> entries = TestDataFactory.getTimesheetEntries(timesheet.Id);
		insert entries;

		TimesheetRegistrationController.TimesheetWrapper wrapper = TimesheetRegistrationController.getData(timesheet.Id);

		String professionalName = wrapper.entries[0].timelogs[0].Timesheet__r.Professional__r.Name;


		PageReference thePage = new PageReference('/apex/TimesheetExport');
		thePage.getParameters().put('recordid', timesheet.Id);
		Test.setCurrentPage(thePage);

		Test.startTest();
		TimesheetExportController controller = new TimesheetExportController();
		Test.stopTest();

		Assert.areEqual(professionalName, controller.professional);
	}
}