force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Default_vendor_contact__c/Default_vendor_contact__c.object-meta.xml
<CustomObject>
    <description>Connector between a Vendor and corresponding unique contact that&apos;s the &quot;default&quot; contact</description>
    <label>Default vendor contact</label>
    <nameField>
        <label>Default contact for vendor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Default vendor contact</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Default_vendor_contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Default vendor contact</relationshipLabel>
    <relationshipName>Default_vendor_contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Default_vendor_contact__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Default vendor contact</relationshipLabel>
    <relationshipName>Default_vendor_contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mailtemplate_Mapping__mdt/Mailtemplate_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Mailtemplate Mapping</label>
    <pluralLabel>Mailtemplate Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Mailtemplate_Mapping__mdt/fields/Mailtemplate_Id__c.field-meta.xml
<CustomField>
    <fullName>Mailtemplate_Id__c</fullName>
    <label>Mailtemplate Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Function title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Deadline_candidate_submission__c.field-meta.xml
<CustomField>
    <fullName>Deadline_candidate_submission__c</fullName>
    <label>Deadline candidate submission</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Hiring_manager__c.field-meta.xml
<CustomField>
    <fullName>Hiring_manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Positions (Hiring manager)</relationshipLabel>
    <relationshipName>Hiring_manager_for_positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Number_of_hires__c.field-meta.xml
<CustomField>
    <fullName>Number_of_hires__c</fullName>
    <label>Number of hires</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Positions (Position)</relationshipLabel>
    <relationshipName>Positions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Processing_status__c.field-meta.xml
<CustomField>
    <fullName>Processing_status__c</fullName>
    <label>Processing status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Distributed</fullName>
            </value>
            <value>
                <fullName>Candidates offered and in review of manager</fullName>
            </value>
            <value>
                <fullName>Interviews planned</fullName>
            </value>
            <value>
                <fullName>Placement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Afgewezen</label>
            </value>
            <value>
                <fullName>Concept</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Applications with hiring manager</fullName>
                <isActive>false</isActive>
                <label>Applications with hiring manager</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Sent to hiring manager</fullName>
                <isActive>false</isActive>
                <label>Sent to hiring manager</label>
            </value>
            <value>
                <fullName>Unapproved</fullName>
                <isActive>false</isActive>
                <label>Unapproved</label>
            </value>
            <value>
                <fullName>Up for correction</fullName>
                <isActive>false</isActive>
                <label>Up for correction</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position_category__c/Position_category__c.object-meta.xml
<CustomObject>
    <label>Position category</label>
    <nameField>
        <label>Position category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Position categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position_category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Position categories</relationshipLabel>
    <relationshipName>Position_categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position_category__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Position categories</relationshipLabel>
    <relationshipName>Position_categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_contact_categories__c/Vendor_contact_categories__c.object-meta.xml
<CustomObject>
    <label>Vendor contact category</label>
    <nameField>
        <label>Vendor contact categories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors contacts categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_contact_categories__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Vendors contacts categories</relationshipLabel>
    <relationshipName>Vendors_contacts_categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_contact_categories__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Vendors contacts categories</relationshipLabel>
    <relationshipName>Vendors_contacts_categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_contact_categories__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendors contacts categories (Vendor)</relationshipLabel>
    <relationshipName>Vendors_contacts_categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_position_application__c/Vendor_position_application__c.object-meta.xml
<CustomObject>
    <description>Object used to store information about applications on a position per vendor, such as number of applications a vendor has made on a position.</description>
    <label>Vendor position application</label>
    <nameField>
        <label>Vendor position application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor position applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_position_application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Vendor position applications</relationshipLabel>
    <relationshipName>Vendor_position_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_position_application__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendor position applications</relationshipLabel>
    <relationshipName>Vendor_position_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VendorsByCategoryController.cls
public without sharing class VendorsByCategoryController {
	class VendorsByCategoryControllerException extends Exception {}
	@AuraEnabled
	public static Boolean areRequiredFieldsFilled(Id positionId) {
		Position__c position = [SELECT Number_of_hires__c, Deadline_candidate_submission__c FROM Position__c WHERE Id = :positionId];

		if(String.isBlank(position?.Number_of_hires__c) || position?.Deadline_candidate_submission__c == null) {
			return false;
		} else {
			return true;
		}
	}
	
	@AuraEnabled
	public static Integer doesPositionCategoryExist(Id positionId) {
		return [SELECT COUNT() FROM Position_category__c WHERE Position__c = :positionId];
	}

	@AuraEnabled
	public static VendorList getVendors(Id positionId) {
		VendorList vendorList = new VendorList();
		vendorList.matchingVendors = new List<Vendor>();
		vendorList.remainingVendors = new List<Vendor>();

		// Query all Position_category__c records related to the given positionId
		Set<Id> categoryIds = new Set<Id>();
		for (Position_category__c positionCategory : [SELECT Category__c FROM Position_category__c WHERE Position__c = :positionId]) {
			categoryIds.add(positionCategory.Category__c);
		}
		
		// Query Vendor_contact_categories__c records related to the categoryIds
		List<Vendor_contact_categories__c> vendorContactCategories = [SELECT Vendor__c, Vendor__r.Name, Category__r.Name FROM Vendor_contact_categories__c WHERE Category__c IN :categoryIds];

		// Loop through vendorContactCategories and map categories per vendor
		Map<Id, Set<String>> categoryMap = new Map<Id, Set<String>>();
		Map<Id, String> vendorNamePerVendorIdMap = new Map<Id, String>();

		for (Vendor_contact_categories__c vcc : vendorContactCategories) {
			if(!categoryMap.containsKey(vcc.Vendor__c)){
				categoryMap.put(vcc.Vendor__c, new Set<String>());
			}

			categoryMap.get(vcc.Vendor__c).add(vcc.Category__r.Name);
			vendorNamePerVendorIdMap.put(vcc.Vendor__c, vcc.Vendor__r.Name);
		}

		Set<Id> vendorsAlreadyDistributed = getVendorsAlreadyDistributed(positionId);

		List<Vendor> vendors = new List<Vendor>();
		List<Vendor> vendorsNotDistributed = new List<Vendor>();
		List<Vendor> vendorsDistributed = new List<Vendor>();

		for(Id recordId : vendorNamePerVendorIdMap.keySet()){
			if(recordId != null){
				List<String> categories = new List<String>(categoryMap.get(recordId));
				categories.sort();

				Vendor vendor = new Vendor();
				vendor.Id = recordId;
				vendor.Name = vendorNamePerVendorIdMap.get(recordId);
				vendor.Categories = String.join(categories, ', ');
				vendor.Distributed = vendorsAlreadyDistributed.contains(recordId) ?? false;

				if(vendor.Distributed == true){
					vendor.Checked = false;
					vendorsDistributed.add(vendor);
				}else{
					vendor.Checked = true;
					vendorsNotDistributed.add(vendor);
				}

				System.debug('vendor');
				System.debug(vendor);
			}
		}
		
		vendors.addAll(vendorsNotDistributed);
		vendors.addAll(vendorsDistributed);
		vendorList.matchingVendors.addAll(vendors);

		List<Account> remainingVendors = [SELECT Id, Name FROM Account WHERE (NOT Id IN :categoryMap.keySet()) AND RecordTypeId = :SchemaUtils.getRecordTypeId('Account', 'Vendor') ORDER BY Name ASC];

		if(!remainingVendors.isEmpty()){
		 	vendors = new List<Vendor>();
			vendorsNotDistributed = new List<Vendor>();
			vendorsDistributed = new List<Vendor>();

			for(Account v : remainingVendors){
				Vendor vendor = new Vendor();
				vendor.Id = v.Id;
				vendor.Name = v.Name;
				vendor.Categories = '';
				vendor.Checked = false;
				vendor.Distributed = vendorsAlreadyDistributed.contains(v.Id) ?? false;

				if(vendor.Distributed == true){
					vendorsDistributed.add(vendor);
				}else{
					vendorsNotDistributed.add(vendor);
				}
			}

			vendors.addAll(vendorsNotDistributed);
			vendors.addAll(vendorsDistributed);
			vendorList.remainingVendors.addAll(vendors);
		}

		return vendorList;
	}

	@TestVisible
	public class VendorList {
		@AuraEnabled public List<Vendor> matchingVendors;
		@AuraEnabled public List<Vendor> remainingVendors;
	}

	@TestVisible
	public class Vendor {
		@AuraEnabled public Id Id;
		@AuraEnabled public String Name;
		@AuraEnabled public String Categories;
		@AuraEnabled public Boolean Checked;
		@AuraEnabled public Boolean Distributed;
	}

	// TODO in the future add the customer ID as a parameter and get all vendors relevant to the customer
	public static Set<Id> getVendorsAlreadyDistributed(Id positionId){
		Set<Id> vendorsAlreadyDistributed = new Set<Id>();
		
		Map<Id, Account> vendorMap = new Map<Id, Account>([SELECT Id FROM Account WHERE RecordTypeId = :SchemaUtils.getRecordTypeId('Account', 'Vendor')]);
		
		for(Vendor_position_application__c value : [SELECT Vendor__c FROM Vendor_position_application__c WHERE Vendor__c IN :vendorMap.keySet() AND Position__c = :positionId]){
			if(vendorMap.containsKey(value.Vendor__c)){
				vendorsAlreadyDistributed.add(value.Vendor__c);
			}
		}

		return vendorsAlreadyDistributed;
	}

	/*
		Get default contacts, and via default contacts get mail adresses from contact
		Then send mails to that email adresses
	*/
	@AuraEnabled()
	public static void sendToVendors(Id positionId, List<Id> vendorIds){
		Position__c p = [SELECT Id, End_date__c, Hiring_manager__c, Deadline_candidate_submission__c FROM Position__c WHERE Id = :positionId LIMIT 1];

		// Get default contact id's
		List<Default_vendor_contact__c> defaultContacts = [SELECT Id, Contact__c, Vendor__c FROM Default_vendor_contact__c WHERE Vendor__c IN :vendorIds];
		
		List<Id> contactIds = new List<Id>();

		// Add Contact__c to list
		for(Default_vendor_contact__c contact : defaultContacts){
			contactIds.add(contact.Contact__c);
		}
		
		// Send mail to vendors
		sendMail(p, contactIds);

		// Create tasks for vendors
		createNewPositionTaskForVendors(p, vendorIds);

		// Creates connection between position and vendor
		handleCreateVendorPositionApplication(positionId, vendorIds);

		// Updates status and processing status
		Position__c updatePos = new Position__c();
		updatePos.Id = positionId;
		updatePos.Status__c = 'Open';
		updatePos.Processing_status__c = 'Distributed';
		update updatePos;
	}

	public static void sendMail(Position__c p, List<Id> contactIds){
		List<Messaging.SingleEmailMessage> sendList = new List<Messaging.SingleEmailMessage>();
		for(Id contactId : contactIds){
			Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
			mail.setTemplateId(Mailtemplate_Mapping__mdt.getInstance('Position_to_Vendor').Mailtemplate_Id__c);
			mail.setWhatId(p.id);
			mail.setTargetObjectId(contactId);
			mail.setToAddresses(new List<String>{contactId});
			sendList.add(mail);
		}

		try {
			List<Messaging.SendEmailResult> mrs =  Messaging.sendEmail(sendList, false);
			System.debug(mrs);
			for(Messaging.SendEmailResult mr : mrs){
				if(mr.isSuccess() != true){
					throw new VendorsByCategoryControllerException('Mail not sent. Error: ' + mr.errors);
				}
			 }
		}catch (Exception e) {
		 	throw new AuraHandledException(e.getMessage());
		}
	}

	public static void createNewPositionTaskForVendors(Position__c p, List<Id> vendorIds){
		List<TaskHandler.TaskWrapper> taskWrappers = new List<TaskHandler.TaskWrapper>();
		
		Map<Id, User> users = new Map<Id, User>([SELECT Id FROM User WHERE ContactId IN (SELECT Contact__c FROM Default_vendor_contact__c WHERE Vendor__c IN :vendorIds)]);

		for(Id userId : users.keySet()){
			TaskHandler.TaskWrapper wrapperNewPosition = new TaskHandler.TaskWrapper('new_position_for_vendor', p.Id, userId, p.Deadline_candidate_submission__c);
			taskWrappers.add(wrapperNewPosition);
		}

		if(taskWrappers.size() > 0){
			TaskHandler.createTasks(taskWrappers);
		}
	}

	@TestVisible
	private static Database.SaveResult [] handleCreateVendorPositionApplication(Id recordId, List<Id> vendorIds) {
		Position__c pos = [SELECT Id FROM Position__c WHERE Id =: recordId LIMIT 1];

		List<Vendor_position_application__c> vendorPositionConnections = new List<Vendor_position_application__c>();

		for (Id vendorId: vendorIds) {
			Vendor_position_application__c conn = new Vendor_position_application__c();

			conn.Position__c = recordId;
			conn.Vendor__c = vendorId;

			vendorPositionConnections.add(conn);
		}

		Database.SaveResult[] res = Database.insert(vendorPositionConnections);

		return res;
	}
}