force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Function title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Deadline_candidate_submission__c.field-meta.xml
<CustomField>
    <fullName>Deadline_candidate_submission__c</fullName>
    <label>Deadline candidate submission</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Positions (Position)</relationshipLabel>
    <relationshipName>Positions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Processing_status__c.field-meta.xml
<CustomField>
    <fullName>Processing_status__c</fullName>
    <label>Processing status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Distributed</fullName>
            </value>
            <value>
                <fullName>Candidates offered and in review of manager</fullName>
            </value>
            <value>
                <fullName>Interviews planned</fullName>
            </value>
            <value>
                <fullName>Placement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Afgewezen</label>
            </value>
            <value>
                <fullName>Concept</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Applications with hiring manager</fullName>
                <isActive>false</isActive>
                <label>Applications with hiring manager</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Sent to hiring manager</fullName>
                <isActive>false</isActive>
                <label>Sent to hiring manager</label>
            </value>
            <value>
                <fullName>Unapproved</fullName>
                <isActive>false</isActive>
                <label>Unapproved</label>
            </value>
            <value>
                <fullName>Up for correction</fullName>
                <isActive>false</isActive>
                <label>Up for correction</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position_category__c/Position_category__c.object-meta.xml
<CustomObject>
    <label>Position category</label>
    <nameField>
        <label>Position category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Position categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position_category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Position categories</relationshipLabel>
    <relationshipName>Position_categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position_category__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Position categories</relationshipLabel>
    <relationshipName>Position_categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PositionTriggerHandlerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class PositionTriggerHandlerTest {

    @istest
    static void  testAccountAdded() {
        Position__c p = TestDataFactory.getPosition(false);
        System.assert(TestUtils.accountWasAdded(p, 'Position__c'));
    }

    @istest
    static void testCreateTask(){
        Position__c pos = TestDataFactory.getPosition(false);
        pos.Deadline_candidate_submission__c = date.today();
        pos.Status__c = 'Open';


        Test.startTest();
        insert pos;
        Test.stopTest();

        List<Task> createdTask = [SELECT Id FROM Task];
        Assert.areEqual(2, createdTask.size());
    }

    // @isTest
    // static void testLockCategory() {

    //     Position__c pos = TestDataFactory.getPosition(false);
    //     pos.Status__c = 'Open';
    //     insert pos;

    //     Category__c cat = TestDataFactory.getCategory('IT');

    //     insert cat;

    //     Position_category__c pc = TestDataFactory.getPositionCategory(pos.Id, cat.Id);

    //     insert pc;

    //     Position__c updatePos = new Position__c();
    //     updatePos.Id = pos.Id;

    //     Test.startTest();
    //     updatePos.Processing_status__c = 'Distributed';
    //     update updatePos;

    //     pc = [SELECT Id FROM Position_category__c WHERE Position__c = :pos.Id LIMIT 1];
    //     Test.stopTest();
        
    //     System.assert(Approval.isLocked(pc.Id));
    // }

    @isTest
    static void testSetInitialStatus() {
        Position__c pos = TestDataFactory.getPosition(false);

        insert pos;

        Test.startTest();
        Position__c res = [SELECT Status__c, Processing_status__c FROM Position__c WHERE Id=:pos.Id LIMIT 1];
        Test.stopTest();

        System.assertEquals('New', res.Processing_status__c, 'Status not New after insert');
    }
}