force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Categories</relationshipLabel>
    <relationshipName>Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Default_vendor_contact__c/Default_vendor_contact__c.object-meta.xml
<CustomObject>
    <description>Connector between a Vendor and corresponding unique contact that&apos;s the &quot;default&quot; contact</description>
    <label>Default vendor contact</label>
    <nameField>
        <label>Default contact for vendor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Default vendor contact</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Default_vendor_contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Default vendor contact</relationshipLabel>
    <relationshipName>Default_vendor_contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Default_vendor_contact__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Default vendor contact</relationshipLabel>
    <relationshipName>Default_vendor_contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Function title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Account_for_positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Positions (Position)</relationshipLabel>
    <relationshipName>Positions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position_category__c/Position_category__c.object-meta.xml
<CustomObject>
    <label>Position category</label>
    <nameField>
        <label>Position category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Position categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position_category__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Position categories</relationshipLabel>
    <relationshipName>Position_categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position_category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Position categories</relationshipLabel>
    <relationshipName>Position_categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position_category__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Position categories</relationshipLabel>
    <relationshipName>Position_categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_contact_categories__c/Vendor_contact_categories__c.object-meta.xml
<CustomObject>
    <label>Vendor contact category</label>
    <nameField>
        <label>Vendor contact categories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors contacts categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_contact_categories__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendor contact category</relationshipLabel>
    <relationshipName>vendor_contact_category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_contact_categories__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Vendors contacts categories</relationshipLabel>
    <relationshipName>Vendors_contacts_categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_contact_categories__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Vendors contacts categories</relationshipLabel>
    <relationshipName>Vendors_contacts_categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_contact_categories__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendors contacts categories (Vendor)</relationshipLabel>
    <relationshipName>Vendors_contacts_categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_position_application__c/Vendor_position_application__c.object-meta.xml
<CustomObject>
    <description>Object used to store information about applications on a position per vendor, such as number of applications a vendor has made on a position.</description>
    <label>Vendor position application</label>
    <nameField>
        <label>Vendor position application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor position applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_position_application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Vendor position applications</relationshipLabel>
    <relationshipName>Vendor_position_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_position_application__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendor position applications</relationshipLabel>
    <relationshipName>Vendor_position_applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VendorsByCategoryControllerTest.cls
@istest
public class VendorsByCategoryControllerTest {
    @istest
	static void doesPositionCategoryExistTest() {
		Position__c p = TestDataFactory.getPosition(true);
		insert p;

		Category__c c = new Category__c();
		c.Name = 'Programming';
		c.Account__c = p.Account__c;
		insert c;

		Position_category__c pC = new Position_category__c();
		pC.Position__c = p.Id;
		pc.Category__c = c.Id;
		pC.Account__c = p.Account__c;
		insert pC;
		
		Test.startTest();
		Integer result = VendorsByCategoryController.doesPositionCategoryExist(p.Id);
		Test.stopTest();

		Assert.isTrue(result > 0);
	}

	@istest
	static void getVendorsWithMatchingCategoriesTest() {
		Position__c p = TestDataFactory.getPosition(true);
		insert p;

		Category__c c = new Category__c();
		c.Name = 'Programming';
		c.Account__c = p.Account__c;
		insert c;

		Position_category__c pC = new Position_category__c();
		pC.Position__c = p.Id;
		pc.Category__c = c.Id;
		pC.Account__c = p.Account__c;
		insert pC;
		
		// Vendor__c v = TestDataFactory.getVendor();
		// insert v;

		Vendor_contact_categories__c vCC = new Vendor_contact_categories__c();
		// vCC.Vendor__c = v.Id;
		vCC.Category__c = c.Id;
		vCC.Account__c = p.Account__c;
		insert vCC;
		
		Test.startTest();
		VendorsByCategoryController.VendorList vendors = VendorsByCategoryController.getVendors(p.Id);
		Test.stopTest();

		// Assert.isTrue(!vendors.isEmpty());
	}

	// @istest
	// static void getRemainingVendorsTest() {
	// 	Position__c p = TestDataFactory.getPosition(true);
	// 	insert p;

	// 	Category__c c = new Category__c();
	// 	c.Name = 'Programming';
	// 	c.Account__c = p.Account__c;
	// 	insert c;

	// 	Position_category__c pC = new Position_category__c();
	// 	pC.Position__c = p.Id;
	// 	pc.Category__c = c.Id;
	// 	pC.Account__c = p.Account__c;
	// 	insert pC;
		
	// 	Account v = TestDataFactory.getVendor();
	// 	insert v;

	// 	Vendor_contact_categories__c vCC = new Vendor_contact_categories__c();
	// 	vCC.Vendor__c = v.Id;
	// 	vCC.Category__c = c.Id;
	// 	vCC.Account__c = p.Account__c;
	// 	insert vCC;
		
	// 	Test.startTest();
	// 	List<VendorsByCategoryController.VendorList> vendors = VendorsByCategoryController.getRemainingVendors(p.Id);
	// 	Test.stopTest();

	// 	System.assert(vendors.isEmpty());
	// }

	@istest
	static void sendToVendorsTest() {
		Account a = TestDataFactory.getAccount();
		insert a;

		Position__c p = TestDataFactory.getPosition(false);
		insert p;

		User u = TestDataFactory.getUser(a);
        insert u;

		Account v = TestDataFactory.getVendor();
		insert v;

		List<Id> vendorIds = new List<Id>();
		vendorIds.add(v.Id);

		Test.startTest();
		VendorsByCategoryController.sendToVendors(p.Id, vendorIds);
		Test.stopTest();

		List<Vendor_position_application__c> conns = [SELECT Position__c, Vendor__c FROM Vendor_position_application__c WHERE Position__c = :p.Id AND Vendor__c = :v.Id];

		System.assertEquals(vendorIds.size(), conns.size());
	}

	@istest
	static void createNewPositionTaskForVendorsTest() {
		Account v = TestDataFactory.getVendor();
		insert v;
		
		Contact c = [SELECT Id FROM Contact WHERE Id IN (SELECT Contact__c FROM Default_vendor_contact__c WHERE Vendor__c = :v.Id) LIMIT 1];

        User u = TestDataFactory.getPortalUser(v, c);
        insert u;

		Position__c p = TestDataFactory.getPosition(false);
		p.End_date__c = System.today().addDays(10);
		insert p;

		List<Id> vendorIds = new List<Id>();
		vendorIds.add(v.Id);

		Test.startTest();
		VendorsByCategoryController.createNewPositionTaskForVendors(p, vendorIds);
		Test.stopTest();

		List<Task> tasks = [SELECT Id, WhatId FROM Task WHERE Type = 'new_position_for_vendor' AND WhatId = :p.Id];

		Assert.areEqual(1, tasks.size());
	}
}