force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Function title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Positions (Position)</relationshipLabel>
    <relationshipName>Positions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position_category__c/Position_category__c.object-meta.xml
<CustomObject>
    <label>Position category</label>
    <nameField>
        <label>Position category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Position categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position_category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Position categories</relationshipLabel>
    <relationshipName>Position_categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position_category__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Position categories</relationshipLabel>
    <relationshipName>Position_categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_contact_categories__c/Vendor_contact_categories__c.object-meta.xml
<CustomObject>
    <label>Vendor contact category</label>
    <nameField>
        <label>Vendor contact categories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors contacts categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_contact_categories__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Vendors contacts categories</relationshipLabel>
    <relationshipName>Vendors_contacts_categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_contact_categories__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendors contacts categories (Vendor)</relationshipLabel>
    <relationshipName>Vendors_contacts_categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CategoriesControllerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class CategoriesControllerTest {

    @isTest
    static void testAddRemovePositionCategory() {
        Category__c finance = TestDataFactory.getCategory('Finance');
        Category__c controlling = TestDataFactory.getCategory('Controlling');

        insert finance;
        insert controlling;

        Position__c pos = TestDataFactory.getPosition(false);

        insert pos;

        test.startTest();
        CategoriesController.addCategories(pos.Id, new List<Id>{finance.Id, controlling.Id});

        System.assert([SELECT Id FROM Position_category__c WHERE Position__c = :pos.Id].size() == 2);

        CategoriesController.removeCategory(pos.Id, finance.Id);

        System.assert([SELECT Id FROM Position_category__c WHERE Position__c = :pos.Id].size() == 1);
        test.stopTest();
    }

    @isTest
    static void testAddRemoveVendorCategory() {
        Category__c finance = TestDataFactory.getCategory('Finance');
        Category__c controlling = TestDataFactory.getCategory('Controlling');

        insert finance;
        insert controlling;

        Account vend = TestDataFactory.getVendor();

        insert vend;

        test.startTest();
        CategoriesController.addCategories(vend.Id, new List<Id>{finance.Id, controlling.Id});

        System.assert([SELECT Id FROM Vendor_contact_categories__c WHERE Vendor__c = :vend.Id].size() == 2);

        CategoriesController.removeCategory(vend.Id, finance.Id);

        System.assert([SELECT Id FROM Vendor_contact_categories__c WHERE Vendor__c = :vend.Id].size() == 1);
        test.stopTest();
    }

    @isTest
    static void testGetVendorCategories() {
        Category__c finance = TestDataFactory.getCategory('Finance');
        Category__c controlling = TestDataFactory.getCategory('Controlling');

        insert finance;
        insert controlling;

        Account vend = TestDataFactory.getVendor();

        insert vend;

        Vendor_contact_categories__c vendCat1 = TestDataFactory.getVendorCategory(vend.Id, finance.Id);

        insert vendCat1;

        Test.startTest();
        List<CategoriesController.CategoryInfo> categories = CategoriesController.getCategories(vend.Id, 'record');
        Test.stopTest();

        System.assert(categories.size() == 2);

        for (CategoriesController.CategoryInfo inf: categories) {
            if (inf.id == finance.Id) {
                System.assert(inf.selected == true);
            }
            else {
                System.assert(inf.selected == false);
            }
        }
    }

    @isTest
    static void testGetPositionCategories() {
        Category__c finance = TestDataFactory.getCategory('Finance');
        Category__c controlling = TestDataFactory.getCategory('Controlling');

        insert finance;
        insert controlling;

        Position__c pos = TestDataFactory.getPosition(false);

        insert pos;

        Position_category__c posCat1 = TestDataFactory.getPositionCategory(pos.Id, finance.Id);
        Position_category__c posCat2 = TestDataFactory.getPositionCategory(pos.Id, controlling.Id);

        insert posCat1;
        insert posCat2;

        List<CategoriesController.CategoryInfo> categories = CategoriesController.getCategories(pos.Id, 'record');

        System.assert(categories.size() == 2);

        for (CategoriesController.CategoryInfo inf: categories) {
            System.assert(inf.selected == true);
        }
    }
}