force-app/main/default/objects/Criterium__mdt/Criterium__mdt.object-meta.xml
<CustomObject>
    <description>Defines a condition based on a field and value</description>
    <label>Criterium</label>
    <pluralLabel>Criteria</pluralLabel>
</CustomObject>

force-app/main/default/objects/Criterium__mdt/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>equals</fullName>
                <default>true</default>
                <label>equals</label>
            </value>
            <value>
                <fullName>not equals</fullName>
            </value>
            <value>
                <fullName>in</fullName>
            </value>
            <value>
                <fullName>is blank</fullName>
            </value>
            <value>
                <fullName>is not blank</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Criterium__mdt/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <description>API name of the field</description>
    <inlineHelpText>API name of the field</inlineHelpText>
    <label>Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Criterium__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Record type</fullName>
                <default>true</default>
                <label>Record type</label>
            </value>
            <value>
                <fullName>Field value</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Criterium__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Add the value(s) that complete the condition you want to evaluate. If you have chosen &quot;in&quot; as your condition, make sure items of the list are separated by a comma. For boolean values, use &apos;true&apos; or &apos;false&apos;.</description>
    <inlineHelpText>Add the value(s) that complete the condition you want to evaluate. If you have chosen &quot;in&quot; as your condition, make sure items of the list are separated by a comma. For boolean values, use &apos;true&apos; or &apos;false&apos;.</inlineHelpText>
    <label>Value(s)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Portal_button_approval_submitter__mdt/Portal_button_approval_submitter__mdt.object-meta.xml
<CustomObject>
    <description>Determines who can submit a record for approval</description>
    <label>Portal button approval submitter</label>
    <pluralLabel>Portal button approval submitters</pluralLabel>
</CustomObject>

force-app/main/default/objects/Portal_button_approval_submitter__mdt/fields/Group_name__c.field-meta.xml
<CustomField>
    <fullName>Group_name__c</fullName>
    <description>If type is &apos;Group&apos;, supply name of the public group here.</description>
    <inlineHelpText>If type is &apos;Group&apos;, supply name of the public group here.</inlineHelpText>
    <label>Group name</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Portal_button_approval_submitter__mdt/fields/Role_name__c.field-meta.xml
<CustomField>
    <fullName>Role_name__c</fullName>
    <description>If type is &apos;Role&apos;, supply name of the role here.</description>
    <inlineHelpText>If type is &apos;Role&apos;, supply name of the role here.</inlineHelpText>
    <label>Role name</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Portal_button_approval_submitter__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Determines who can submit record for submission.</description>
    <inlineHelpText>Determines who can submit record for submission.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Record owner</fullName>
                <default>true</default>
                <label>Record owner</label>
            </value>
            <value>
                <fullName>Role</fullName>
            </value>
            <value>
                <fullName>Public group</fullName>
            </value>
            <value>
                <fullName>Record creator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Portal_button_filter__mdt/Portal_button_filter__mdt.object-meta.xml
<CustomObject>
    <description>Connect criterium, for example: Name EQUALS &apos;Bob&apos; for filtering by name, to visibility setting and numbers the condition that&apos;s formed this way for use in filter logic.</description>
    <label>Portal button filter</label>
    <pluralLabel>Portal button filters</pluralLabel>
</CustomObject>

force-app/main/default/objects/Portal_button_filter__mdt/fields/Criterium__c.field-meta.xml
<CustomField>
    <fullName>Criterium__c</fullName>
    <description>Determines what logic applies to this filter.</description>
    <inlineHelpText>Determines what logic applies to this filter.</inlineHelpText>
    <label>Criterium</label>
    <referenceTo>Criterium__mdt</referenceTo>
    <relationshipLabel>Portal button filters</relationshipLabel>
    <relationshipName>Portal_button_filters</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Portal_button_filter__mdt/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <description>Identifier for filter, used in filter logic formula on Portal button visbility record. You have to fill this manually and make sure it is unique, because we can&apos;t have triggers on custom metadata (sorry). Numbers higher than 9 are not supported because I wrote the parsing lazily.</description>
    <inlineHelpText>Identifier for filter, used in filter logic formula on Portal button visbility record. You have to fill this manually and make sure it is unique, because we can&apos;t have triggers on custom metadata (sorry). Numbers higher than 9 are not supported because I wrote the parsing lazily.</inlineHelpText>
    <label>Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PortalButtonVisibilityEvaluator.cls
public with sharing class PortalButtonVisibilityEvaluator {
    public class PortalButtonVisibilityEvaluatorException extends Exception {}

    private static Boolean evaluateCondition(String value, String expectedValue, String operator) {
        System.debug('Evaluate condition ' + value + ' ' + operator + ' ' + expectedValue);
        Boolean result = false;
        switch on operator {
            when 'in' {
                List<String> expectedValues = expectedValue.split(',');
                result = expectedValues.contains(value);
            }
            when 'equals'{
                result = (value == expectedValue);
            }
            when 'not equals' {
                result = !(value == expectedValue);
            }
            when 'is blank' {
                result = String.isBlank(value);
            }
            when 'is not blank' {
                result = String.isNotBlank(value);
            }
            when else {
                throw new PortalButtonVisibilityEvaluatorException('Unexpected operator ' + operator + '. Could not determine truth value.');
            }
        }

        System.debug(' is: ' + result);
        return result;
    }

    private static Boolean evaluateCriterium(String objectName, SObject record, Criterium__mdt criterium) {
        String operator = criterium.Condition__c;
        String value;
        String expectedValue = criterium.Value__c;

        System.debug('expected value ' + criterium.Value__c);
        System.debug('Operator ' + operator);

        if (criterium.Type__c == 'Record type') {
            value = SchemaUtils.getRecordTypeName(objectName, (Id)record.get('RecordTypeId'));
            System.debug('Value ' + value);
        }
        else if (criterium.Type__c == 'Field value') {
            value = DeveloperUtils.getFieldValueAsString(record, criterium.Field__c);
            System.debug('value ' + value);
        }

        return evaluateCondition(value, expectedValue, operator);
    }

    /* This does NOT work if the highest filter number is greater than 9, since we will introduce substitution errors */
    public static Boolean evaluateFilterLogic(String filterLogic, Map<Integer, Boolean> truthByConditionNumber) {
        String logic = filterLogic;

        System.debug('TRUTH BY CONDITION ' + truthByConditionNumber);
        // If no logic is specified, all conditions need to be true
        if (String.isBlank(logic)) {
            Set<Integer> s = truthByConditionNumber.keySet();
            Set<String> b = new Set<String>();
            for (Integer n: truthByConditionNumber.keySet()) {
                b.add(String.valueOf(n));
            }

            logic = String.join(b, ' AND ');
        }

        String res = logic;
        for (Integer n: truthByConditionNumber.keySet()) {
            res = res.replace(String.valueOf(n), truthByConditionNumber.get(n)? 'true' : 'false');
        }

        res = res.replace('true', '1');
        res = res.replace('false', '0');
        System.debug('TOKENIZED: ' + res);
        return FilterLogicEvaluator.evaluate(res);
    }

    /* Evaluates all filters, check whether there is any filter logic (of not just returns whether all filters are true).
    If there is filter logic, we substitute the corresponding truth values from the filters into it, then evaluate it Boolean value. */
    public static Boolean evaluateFilters(Id userId, String objectName, String filterLogic, List<Portal_button_filter__mdt> filters, SObject record) {
        Map<Integer, Boolean> truthByFilterNumber = new Map<Integer, Boolean>();

        for (Portal_button_filter__mdt filter: filters) {
            System.debug('FILTER NUMBER: ' + filter.Number__c);
            Integer ind = (Integer)filter.Number__c;
            if (truthByFilterNumber.get(ind) != null) {
                throw new PortalButtonVisibilityEvaluatorException('Number used for multiple filters (must be unique): ' + String.valueOf(ind));
            }

            truthByFilterNumber.put(ind, evaluateCriterium(objectName, record, filter.Criterium__r));
        }

        return evaluateFilterLogic(filterLogic, truthByFilterNumber);
    }

    /* Evaluates whether user is valid submitter for record to specified approval process */
    public static Boolean evaluateApprovalSubmitter(List<Portal_button_approval_submitter__mdt> validApprovalSubmitters, Id userId, 
    SObject record, List<Group> userGroups) {
        User u = [SELECT UserRole.Name FROM User WHERE Id = :userId];
        Set<String> userGroupNames = null;

        if (userGroups != null) {
            userGroupNames = DeveloperUtils.getStringFieldSet(userGroups, 'Name');
        }
        String userRole = u.UserRole.Name;

        for (Portal_button_approval_submitter__mdt approver: validApprovalSubmitters) {
            String approvalSubmissionRuleType = approver.Type__c;

            switch on approvalSubmissionRuleType {
                when 'Record owner' {
                    if (((Id)record.get('OwnerId') == userId)) return true;
                }
                when 'Record creator' {
                    if (((Id)record.get('CreatedById') == userId)) return true;
                }
                when 'Role' {
                    if (((String)record.get('Role_name__c') == userRole)) return true;
                }
                when 'Public group' {
                    if (userGroups == null)
                        return false;
                    if ((userGroupNames.contains((String)record.get('Group_name__c')))) return true;
                }
                when else {
                    throw new PortalButtonVisibilityEvaluatorException('Unexpected type on Portal_button_approval_submitter__mdt ' + validApprovalSubmitters);
                }
            }
        }

        return false;
    }
}